//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDW.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актуальный статус ОТК 100 последних документов.
        /// </summary>
        public static string ActualStatusOTK {
            get {
                return ResourceManager.GetString("ActualStatusOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый стеллаж.
        /// </summary>
        public static string AddStellag {
            get {
                return ResourceManager.GetString("AddStellag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить улицу.
        /// </summary>
        public static string AddStreet {
            get {
                return ResourceManager.GetString("AddStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть все задания.
        /// </summary>
        public static string AllWorks {
            get {
                return ResourceManager.GetString("AllWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение нескольких номенклатур между складами.
        /// </summary>
        public static string CHGMass {
            get {
                return ResourceManager.GetString("CHGMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дочерние объекты.
        /// </summary>
        public static string Childs {
            get {
                return ResourceManager.GetString("Childs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть BIG код.
        /// </summary>
        public static string CloseBigCode {
            get {
                return ResourceManager.GetString("CloseBigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировка CIN.
        /// </summary>
        public static string CorrectCIN {
            get {
                return ResourceManager.GetString("CorrectCIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дневные результаты.
        /// </summary>
        public static string DayResult {
            get {
                return ResourceManager.GetString("DayResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дневные результаты на дату.
        /// </summary>
        public static string DayResultDate {
            get {
                return ResourceManager.GetString("DayResultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть задания подразделения.
        /// </summary>
        public static string DepartmentWorks {
            get {
                return ResourceManager.GetString("DepartmentWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши перемещения сегодня.
        /// </summary>
        public static string DocksToday {
            get {
                return ResourceManager.GetString("DocksToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Движения.
        /// </summary>
        public static string Dvigeniya {
            get {
                return ResourceManager.GetString("Dvigeniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на единиц.
        /// </summary>
        public static string Edinic {
            get {
                return ResourceManager.GetString("Edinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировка документов.
        /// </summary>
        public static string EditDoc {
            get {
                return ResourceManager.GetString("EditDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить количество в QR.
        /// </summary>
        public static string EditQR {
            get {
                return ResourceManager.GetString("EditQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить перемещение.
        /// </summary>
        public static string EndPeremeshenie {
            get {
                return ResourceManager.GetString("EndPeremeshenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальное кол-во выпуска - 1 шт. Кол-во выпуска должно быть указано целым числом..
        /// </summary>
        public static string ErrorCeloeChislo {
            get {
                return ResourceManager.GetString("ErrorCeloeChislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество превышает максимально допустимое значение..
        /// </summary>
        public static string ErrorMnogo {
            get {
                return ResourceManager.GetString("ErrorMnogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден BOM.
        /// </summary>
        public static string ErrorNeNaidenBOM {
            get {
                return ResourceManager.GetString("ErrorNeNaidenBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено задание, выданное старшим мастером.
        /// </summary>
        public static string ErrorNeNaidenStarWork {
            get {
                return ResourceManager.GetString("ErrorNeNaidenStarWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден WORK.
        /// </summary>
        public static string ErrorNeNaidenWork {
            get {
                return ResourceManager.GetString("ErrorNeNaidenWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен МОЛ склада, выберите вручную.
        /// </summary>
        public static string ErrorNeOpredelenMOL {
            get {
                return ResourceManager.GetString("ErrorNeOpredelenMOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен пользователь, перезайдите в программу.
        /// </summary>
        public static string ErrorNeOpredelenPolzovatel {
            get {
                return ResourceManager.GetString("ErrorNeOpredelenPolzovatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен склад выпуска.
        /// </summary>
        public static string ErrorNeOpredelenSklad {
            get {
                return ResourceManager.GetString("ErrorNeOpredelenSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этой номенклатуры не требуется.
        /// </summary>
        public static string ErrorNeTrebuetsa {
            get {
                return ResourceManager.GetString("ErrorNeTrebuetsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого количества нет в QR коде.
        /// </summary>
        public static string ErrorNetVQR {
            get {
                return ResourceManager.GetString("ErrorNetVQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОТК не пройден или брак! Данный QR код нельзя переместить в НЗП.
        /// </summary>
        public static string ErrorOTKNeProiden {
            get {
                return ResourceManager.GetString("ErrorOTKNeProiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка считывания места!.
        /// </summary>
        public static string ErrorSchitivaniiMesta {
            get {
                return ResourceManager.GetString("ErrorSchitivaniiMesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно выпустить это кол-во.Максимальное кол-во выпуска=.
        /// </summary>
        public static string ErrorVipuskBolsheMax {
            get {
                return ResourceManager.GetString("ErrorVipuskBolsheMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обработке запроса произошла ошибка..
        /// </summary>
        public static string ErrorZapros {
            get {
                return ResourceManager.GetString("ErrorZapros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из программы.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактическое количество.
        /// </summary>
        public static string FaktQTY {
            get {
                return ResourceManager.GetString("FaktQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать BIG QR.
        /// </summary>
        public static string GenerateBIGQR {
            get {
                return ResourceManager.GetString("GenerateBIGQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генерация / восстановление QR.
        /// </summary>
        public static string GenerateQR {
            get {
                return ResourceManager.GetString("GenerateQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите заказ поставщику.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о номенклатуре.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризация.
        /// </summary>
        public static string Inventarizacia {
            get {
                return ResourceManager.GetString("Inventarizacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризационная ведомость.
        /// </summary>
        public static string InvVedomost {
            get {
                return ResourceManager.GetString("InvVedomost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения внес плановый отдел.
        /// </summary>
        public static string IzmeneniyaVnesPlanovi {
            get {
                return ResourceManager.GetString("IzmeneniyaVnesPlanovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить фактический остаток.
        /// </summary>
        public static string IzmenitFactOstatok {
            get {
                return ResourceManager.GetString("IzmenitFactOstatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждаете изменение статуса ОТК?.
        /// </summary>
        public static string IzmenitStatusOTK {
            get {
                return ResourceManager.GetString("IzmenitStatusOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество номенклатуры.
        /// </summary>
        public static string KolichestvoNomenklaturi {
            get {
                return ResourceManager.GetString("KolichestvoNomenklaturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступившее количество.
        /// </summary>
        public static string KolichestvoPostupivshee {
            get {
                return ResourceManager.GetString("KolichestvoPostupivshee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в заказе поставщику.
        /// </summary>
        public static string KolichestvoVZakazePostavshiku {
            get {
                return ResourceManager.GetString("KolichestvoVZakazePostavshiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комплектование WORK по новым QR.
        /// </summary>
        public static string KomplektovanieNew {
            get {
                return ResourceManager.GetString("KomplektovanieNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комплектация задания на производство.
        /// </summary>
        public static string Komplektovka {
            get {
                return ResourceManager.GetString("Komplektovka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комплектация WORK.
        /// </summary>
        public static string KomplektWORK {
            get {
                return ResourceManager.GetString("KomplektWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние движения.
        /// </summary>
        public static string LastDvig {
            get {
                return ResourceManager.GetString("LastDvig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линия сборки.
        /// </summary>
        public static string LiniyaSborki {
            get {
                return ResourceManager.GetString("LiniyaSborki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка файла.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка трёхдневного плана производства.
        /// </summary>
        public static string LoadFileVipuska {
            get {
                return ResourceManager.GetString("LoadFileVipuska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное меню.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MinusovieOstatki.
        /// </summary>
        public static string MinusovieOstatki {
            get {
                return ResourceManager.GetString("MinusovieOstatki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно переместить на пр-во.
        /// </summary>
        public static string MognoPeremestitNaProizvodstvo {
            get {
                return ResourceManager.GetString("MognoPeremestitNaProizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно переместить не более.
        /// </summary>
        public static string MognoPeremestitNeBolee {
            get {
                return ResourceManager.GetString("MognoPeremestitNeBolee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно произвести.
        /// </summary>
        public static string MognoProizvesti {
            get {
                return ResourceManager.GetString("MognoProizvesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материально ответственное лицо.
        /// </summary>
        public static string MOL {
            get {
                return ResourceManager.GetString("MOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МОЛ.
        /// </summary>
        public static string MOL2 {
            get {
                return ResourceManager.GetString("MOL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои документы.
        /// </summary>
        public static string MyDocs {
            get {
                return ResourceManager.GetString("MyDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои поступления на склад.
        /// </summary>
        public static string MyPostuplenies {
            get {
                return ResourceManager.GetString("MyPostuplenies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Находится на складе.
        /// </summary>
        public static string NahoditsaNaSklade {
            get {
                return ResourceManager.GetString("NahoditsaNaSklade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование и парт. номер.
        /// </summary>
        public static string NaimenovanieIPartNomer {
            get {
                return ResourceManager.GetString("NaimenovanieIPartNomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение подразделения.
        /// </summary>
        public static string NaznachenieDepartment {
            get {
                return ResourceManager.GetString("NaznachenieDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначие роли.
        /// </summary>
        public static string NaznachenieRoli {
            get {
                return ResourceManager.GetString("NaznachenieRoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить смену.
        /// </summary>
        public static string NaznachitSmenu {
            get {
                return ResourceManager.GetString("NaznachitSmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить задания в план.
        /// </summary>
        public static string NaznachitZadaniyaVPlan {
            get {
                return ResourceManager.GetString("NaznachitZadaniyaVPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно комплектующих.
        /// </summary>
        public static string NedostatochnoKomplekta {
            get {
                return ResourceManager.GetString("NedostatochnoKomplekta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат невозможен, недостаточно количества номенклатуры в НЗП.
        /// </summary>
        public static string NedostatochnoVNZP {
            get {
                return ResourceManager.GetString("NedostatochnoVNZP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить работу в процессе производства. Воспользуйтесь кнопкой Пропуск на точке выпуска!.
        /// </summary>
        public static string NelzaUdalitWork {
            get {
                return ResourceManager.GetString("NelzaUdalitWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначено.
        /// </summary>
        public static string NeNaznacheno {
            get {
                return ResourceManager.GetString("NeNaznacheno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не производится.
        /// </summary>
        public static string NeProizvoditsa {
            get {
                return ResourceManager.GetString("NeProizvoditsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данной номенклатуры нет на складе.
        /// </summary>
        public static string NetNaSklade {
            get {
                return ResourceManager.GetString("NetNaSklade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в логине или пароле.
        /// </summary>
        public static string NevernyParol {
            get {
                return ResourceManager.GetString("NevernyParol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрано.
        /// </summary>
        public static string NeVibrano {
            get {
                return ResourceManager.GetString("NeVibrano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номенклатура.
        /// </summary>
        public static string Nomenklatura {
            get {
                return ResourceManager.GetString("Nomenklatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номенклатуры недостаточно!.
        /// </summary>
        public static string NomenklaturiNedostatochno {
            get {
                return ResourceManager.GetString("NomenklaturiNedostatochno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер движения.
        /// </summary>
        public static string NomerDvigeniya {
            get {
                return ResourceManager.GetString("NomerDvigeniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На данной точке выпуска больше нет заданий на производство.
        /// </summary>
        public static string NoWorks {
            get {
                return ResourceManager.GetString("NoWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно произвести завтра.
        /// </summary>
        public static string NugnoProizvestiZavtra {
            get {
                return ResourceManager.GetString("NugnoProizvestiZavtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление плана работ.
        /// </summary>
        public static string ObnovleniePlanaRabot {
            get {
                return ResourceManager.GetString("ObnovleniePlanaRabot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет ограничений для выпуска. Выпуск согласно дневному плану..
        /// </summary>
        public static string OgranichenieDay {
            get {
                return ResourceManager.GetString("OgranichenieDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укомплектуйте номенклатуру.
        /// </summary>
        public static string OgranichenieNomenklatura {
            get {
                return ResourceManager.GetString("OgranichenieNomenklatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трехдневный план ограничивает выпуск.
        /// </summary>
        public static string OgranicheniePlan {
            get {
                return ResourceManager.GetString("OgranicheniePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет ограничений на выпуск.
        /// </summary>
        public static string OgranichenieWORK {
            get {
                return ResourceManager.GetString("OgranichenieWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось укомплектовать.
        /// </summary>
        public static string OstalosUkomplektovat {
            get {
                return ResourceManager.GetString("OstalosUkomplektovat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки НЗП.
        /// </summary>
        public static string OstatkiInWork {
            get {
                return ResourceManager.GetString("OstatkiInWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки номенклатуры на складах.
        /// </summary>
        public static string OstatkiNomenklaturi {
            get {
                return ResourceManager.GetString("OstatkiNomenklaturi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки в QR кодах в разрезе статусов ОТК.
        /// </summary>
        public static string OstatkiVRazrezeOTK {
            get {
                return ResourceManager.GetString("OstatkiVRazrezeOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки НЗП в заданиях на производство.
        /// </summary>
        public static string OstatkiVWorks {
            get {
                return ResourceManager.GetString("OstatkiVWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет комплектование заданий на производство.
        /// </summary>
        public static string OtchetKomplekt {
            get {
                return ResourceManager.GetString("OtchetKomplekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОТК.
        /// </summary>
        public static string OTK {
            get {
                return ResourceManager.GetString("OTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонение.
        /// </summary>
        public static string Otklonenie {
            get {
                return ResourceManager.GetString("Otklonenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена проведения.
        /// </summary>
        public static string OtmenaProvedeniya {
            get {
                return ResourceManager.GetString("OtmenaProvedeniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить поиск по QR коду.
        /// </summary>
        public static string OtmenaScanQR {
            get {
                return ResourceManager.GetString("OtmenaScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсканируйте номенклатуру.
        /// </summary>
        public static string OtskaniruiteNomenklaturu {
            get {
                return ResourceManager.GetString("OtskaniruiteNomenklaturu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родитель.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Парт. номер.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимое количество номенклатуры уже передано.
        /// </summary>
        public static string Peredano {
            get {
                return ResourceManager.GetString("Peredano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещаем на производство.
        /// </summary>
        public static string PeremeshaemNaPrVo {
            get {
                return ResourceManager.GetString("PeremeshaemNaPrVo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение на производство.
        /// </summary>
        public static string PeremeshenieNaProizvodstvo {
            get {
                return ResourceManager.GetString("PeremeshenieNaProizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение на склад.
        /// </summary>
        public static string PeremeshenieNaSklad {
            get {
                return ResourceManager.GetString("PeremeshenieNaSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение со склада.
        /// </summary>
        public static string PeremeshenieSoSklada {
            get {
                return ResourceManager.GetString("PeremeshenieSoSklada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение успешно.
        /// </summary>
        public static string PeremeshenieUspeshno {
            get {
                return ResourceManager.GetString("PeremeshenieUspeshno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить на другой склад.
        /// </summary>
        public static string PeremestitNaDrugoiSklad {
            get {
                return ResourceManager.GetString("PeremestitNaDrugoiSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить на производство.
        /// </summary>
        public static string PeremestitNaProizvodstvo {
            get {
                return ResourceManager.GetString("PeremestitNaProizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выпуск ДСЕ и ГП.
        /// </summary>
        public static string PeremestitSProizvodstva {
            get {
                return ResourceManager.GetString("PeremestitSProizvodstva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трехдневный план заданий на производство (отчёт).
        /// </summary>
        public static string Plan3Days {
            get {
                return ResourceManager.GetString("Plan3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планограмма склада.
        /// </summary>
        public static string Planogramma {
            get {
                return ResourceManager.GetString("Planogramma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планограмма поиск номенклатуры.
        /// </summary>
        public static string PlanogrammaSearch {
            get {
                return ResourceManager.GetString("PlanogrammaSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плановый отдел.
        /// </summary>
        public static string Planovi {
            get {
                return ResourceManager.GetString("Planovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подразделение.
        /// </summary>
        public static string Podrazdelenie {
            get {
                return ResourceManager.GetString("Podrazdelenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Podtverdit {
            get {
                return ResourceManager.GetString("Podtverdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить перемещение.
        /// </summary>
        public static string PodtverditDvigenie {
            get {
                return ResourceManager.GetString("PodtverditDvigenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить перемещение.
        /// </summary>
        public static string PodtverditPeremeshenie {
            get {
                return ResourceManager.GetString("PodtverditPeremeshenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить перемещение.
        /// </summary>
        public static string PodtverditPeremeshenieSoSklada {
            get {
                return ResourceManager.GetString("PodtverditPeremeshenieSoSklada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по номеру или имени склада.
        /// </summary>
        public static string PoiskSklada {
            get {
                return ResourceManager.GetString("PoiskSklada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полка.
        /// </summary>
        public static string Polka {
            get {
                return ResourceManager.GetString("Polka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить новое место размещения.
        /// </summary>
        public static string PologitNaPolku {
            get {
                return ResourceManager.GetString("PologitNaPolku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик.
        /// </summary>
        public static string Postavshik {
            get {
                return ResourceManager.GetString("Postavshik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление на склад WIN.
        /// </summary>
        public static string PostuplenieNaSklad {
            get {
                return ResourceManager.GetString("PostuplenieNaSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление на склад (новый QR).
        /// </summary>
        public static string PostuplenieNaSkladMass {
            get {
                return ResourceManager.GetString("PostuplenieNaSkladMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление на склад успешно сохранено!.
        /// </summary>
        public static string PostuplenieSohraneno {
            get {
                return ResourceManager.GetString("PostuplenieSohraneno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление на склад отчет.
        /// </summary>
        public static string PostuplenieWINOtchet {
            get {
                return ResourceManager.GetString("PostuplenieWINOtchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По вашему запросу ничего не найдено.
        /// </summary>
        public static string PoZaprosuNeNaideno {
            get {
                return ResourceManager.GetString("PoZaprosuNeNaideno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напечатать QR код.
        /// </summary>
        public static string PrintQR {
            get {
                return ResourceManager.GetString("PrintQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент.
        /// </summary>
        public static string Procent {
            get {
                return ResourceManager.GetString("Procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процесс комплектования.
        /// </summary>
        public static string ProcessKomplektovaniya {
            get {
                return ResourceManager.GetString("ProcessKomplektovaniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произведено.
        /// </summary>
        public static string Proizvedeno {
            get {
                return ResourceManager.GetString("Proizvedeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо произвести.
        /// </summary>
        public static string Proizvesti {
            get {
                return ResourceManager.GetString("Proizvesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string Proizvodstvo {
            get {
                return ResourceManager.GetString("Proizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропустить.
        /// </summary>
        public static string Propusk {
            get {
                return ResourceManager.GetString("Propusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте статус ОТК.
        /// </summary>
        public static string ProverteStatusOTK {
            get {
                return ResourceManager.GetString("ProverteStatusOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее поступление QIN.
        /// </summary>
        public static string QIN {
            get {
                return ResourceManager.GetString("QIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактический остаток.
        /// </summary>
        public static string QTYFact {
            get {
                return ResourceManager.GetString("QTYFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество к перемещению.
        /// </summary>
        public static string QTYKPeremesheniu {
            get {
                return ResourceManager.GetString("QTYKPeremesheniu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во отпуска.
        /// </summary>
        public static string QTYKPeremesheniyu {
            get {
                return ResourceManager.GetString("QTYKPeremesheniyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно в НЗП.
        /// </summary>
        public static string QTYMustNZP {
            get {
                return ResourceManager.GetString("QTYMustNZP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество на складе.
        /// </summary>
        public static string QTYNaSklade {
            get {
                return ResourceManager.GetString("QTYNaSklade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На данном складе недостаточно номенклатуры.
        /// </summary>
        public static string QTYNaSkladeNedostatochno {
            get {
                return ResourceManager.GetString("QTYNaSkladeNedostatochno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в НЗП.
        /// </summary>
        public static string QTYNZP {
            get {
                return ResourceManager.GetString("QTYNZP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество к перемещению.
        /// </summary>
        public static string QTYPeremestit {
            get {
                return ResourceManager.GetString("QTYPeremestit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во по заданию.
        /// </summary>
        public static string QTYPoProizvodstvennomuZadaniu {
            get {
                return ResourceManager.GetString("QTYPoProizvodstvennomuZadaniu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество поступило.
        /// </summary>
        public static string QTYPostupilo {
            get {
                return ResourceManager.GetString("QTYPostupilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество поступления (в данном QR коде, объекте).
        /// </summary>
        public static string QTYPostupleniya {
            get {
                return ResourceManager.GetString("QTYPostupleniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в QR.
        /// </summary>
        public static string QTYQR {
            get {
                return ResourceManager.GetString("QTYQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в данной партии.
        /// </summary>
        public static string QTYVDannoiPartii {
            get {
                return ResourceManager.GetString("QTYVDannoiPartii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество выпущенного ПФ и ГП на текущую дату.
        /// </summary>
        public static string QTYVipushennogoPF {
            get {
                return ResourceManager.GetString("QTYVipushennogoPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произведено по заданию всего / Количество в задании на производство.
        /// </summary>
        public static string QTYVZadaniiQTYVsego {
            get {
                return ResourceManager.GetString("QTYVZadaniiQTYVsego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в заказе.
        /// </summary>
        public static string QTYVZakaze {
            get {
                return ResourceManager.GetString("QTYVZakaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расход на 1 ед..
        /// </summary>
        public static string Rashod {
            get {
                return ResourceManager.GetString("Rashod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разница.
        /// </summary>
        public static string Raznica {
            get {
                return ResourceManager.GetString("Raznica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузить BOM.
        /// </summary>
        public static string ReloadBOM {
            get {
                return ResourceManager.GetString("ReloadBOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сканирование ГП.
        /// </summary>
        public static string ScanGP {
            get {
                return ResourceManager.GetString("ScanGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсканируйте место размещения.
        /// </summary>
        public static string ScanMesto {
            get {
                return ResourceManager.GetString("ScanMesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсканируйте место размещения.
        /// </summary>
        public static string ScanMestoRazmesheniya {
            get {
                return ResourceManager.GetString("ScanMestoRazmesheniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сканирование QR кода.
        /// </summary>
        public static string ScanNomenklaturs {
            get {
                return ResourceManager.GetString("ScanNomenklaturs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнить автоматически смена 10ч.
        /// </summary>
        public static string SetAutoSmena10 {
            get {
                return ResourceManager.GetString("SetAutoSmena10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнить автоматически смена 8ч.
        /// </summary>
        public static string SetAutoSmena8 {
            get {
                return ResourceManager.GetString("SetAutoSmena8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Схлопнуть строки на выбранном складе.
        /// </summary>
        public static string ShlopnutStroki {
            get {
                return ResourceManager.GetString("ShlopnutStroki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать все задания.
        /// </summary>
        public static string ShowAllZadanies {
            get {
                return ResourceManager.GetString("ShowAllZadanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение со склада.
        /// </summary>
        public static string SkladOtpravitel {
            get {
                return ResourceManager.GetString("SkladOtpravitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Складской учет.
        /// </summary>
        public static string SkladskoiUchet {
            get {
                return ResourceManager.GetString("SkladskoiUchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сличительная ведомость.
        /// </summary>
        public static string SlichitelnayaVedomost {
            get {
                return ResourceManager.GetString("SlichitelnayaVedomost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить пользователя.
        /// </summary>
        public static string SmenitPolzovatelya {
            get {
                return ResourceManager.GetString("SmenitPolzovatelya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус ОТК.
        /// </summary>
        public static string StatusOTK {
            get {
                return ResourceManager.GetString("StatusOTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стеллаж.
        /// </summary>
        public static string Stellag {
            get {
                return ResourceManager.GetString("Stellag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склад.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение из склада.
        /// </summary>
        public static string StockFrom {
            get {
                return ResourceManager.GetString("StockFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение на склад.
        /// </summary>
        public static string StockTo {
            get {
                return ResourceManager.GetString("StockTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторно.
        /// </summary>
        public static string Storno {
            get {
                return ResourceManager.GetString("Storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улица.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СуммаОткл.
        /// </summary>
        public static string SummOtkloneniya {
            get {
                return ResourceManager.GetString("SummOtkloneniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СуммаФакт.
        /// </summary>
        public static string SummQTYFact {
            get {
                return ResourceManager.GetString("SummQTYFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СуммаУчет.
        /// </summary>
        public static string SummUchetOstatok {
            get {
                return ResourceManager.GetString("SummUchetOstatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь распечатайте и наклейте QR код.
        /// </summary>
        public static string TeperRaspechataiteQR {
            get {
                return ResourceManager.GetString("TeperRaspechataiteQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точка выпуска.
        /// </summary>
        public static string TochkaVipuska {
            get {
                return ResourceManager.GetString("TochkaVipuska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип движения.
        /// </summary>
        public static string TypeDvigeniya {
            get {
                return ResourceManager.GetString("TypeDvigeniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учетный остаток.
        /// </summary>
        public static string UchetniOstatok {
            get {
                return ResourceManager.GetString("UchetniOstatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улица.
        /// </summary>
        public static string Ulica {
            get {
                return ResourceManager.GetString("Ulica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Израсходовано.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно!.
        /// </summary>
        public static string Uspeshno {
            get {
                return ResourceManager.GetString("Uspeshno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утвердить комисионно.
        /// </summary>
        public static string UtverditKomisionno {
            get {
                return ResourceManager.GetString("UtverditKomisionno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены?.
        /// </summary>
        public static string Uvereni {
            get {
                return ResourceManager.GetString("Uvereni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуть из НЗП.
        /// </summary>
        public static string VernutIsNZP {
            get {
                return ResourceManager.GetString("VernutIsNZP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться в главное меню.
        /// </summary>
        public static string VGlavnoeMenu {
            get {
                return ResourceManager.GetString("VGlavnoeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите текущего пользователя программы.
        /// </summary>
        public static string ViberitePolzovatelya {
            get {
                return ResourceManager.GetString("ViberitePolzovatelya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите текущего пользователя программы.
        /// </summary>
        public static string ViberitePolzovatelyaProgrammi {
            get {
                return ResourceManager.GetString("ViberitePolzovatelyaProgrammi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнено.
        /// </summary>
        public static string Vipolneno {
            get {
                return ResourceManager.GetString("Vipolneno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выпуск по производственному заданию завершен.
        /// </summary>
        public static string VipuskEnd {
            get {
                return ResourceManager.GetString("VipuskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выпуск по производственному заданию еще не начался.
        /// </summary>
        public static string VipuskNeNachat {
            get {
                return ResourceManager.GetString("VipuskNeNachat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начат выпуск по производственному заданию.
        /// </summary>
        public static string VipuskVProcesse {
            get {
                return ResourceManager.GetString("VipuskVProcesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выпуск завершен! Перейти к следующему &gt;.
        /// </summary>
        public static string VipuskZavershen {
            get {
                return ResourceManager.GetString("VipuskZavershen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите в программу.
        /// </summary>
        public static string VoiditeVProgrammu {
            get {
                return ResourceManager.GetString("VoiditeVProgrammu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в программу.
        /// </summary>
        public static string VoitiVProgrammu {
            get {
                return ResourceManager.GetString("VoitiVProgrammu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможные действия:.
        /// </summary>
        public static string VosmognieDeistviya {
            get {
                return ResourceManager.GetString("VosmognieDeistviya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить QR код.
        /// </summary>
        public static string VosstanovitQR {
            get {
                return ResourceManager.GetString("VosstanovitQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановленный QR.
        /// </summary>
        public static string VosstanovlenniQR {
            get {
                return ResourceManager.GetString("VosstanovlenniQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возвращаем.
        /// </summary>
        public static string Vozvrashaem {
            get {
                return ResourceManager.GetString("Vozvrashaem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В работе.
        /// </summary>
        public static string VRabote {
            get {
                return ResourceManager.GetString("VRabote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите ваше подразделение.
        /// </summary>
        public static string VvediteDepartment {
            get {
                return ResourceManager.GetString("VvediteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш логин.
        /// </summary>
        public static string VvediteLogin {
            get {
                return ResourceManager.GetString("VvediteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите парт номер.
        /// </summary>
        public static string VveditePartNumber {
            get {
                return ResourceManager.GetString("VveditePartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string VveditePassword {
            get {
                return ResourceManager.GetString("VveditePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели количество номенклатуры больше чем в заказе поставщику! Введите другое количество, другой заказ или обратитесь в отдел поставок для корректировки заказа..
        /// </summary>
        public static string VveliBolsheChemVZakaze {
            get {
                return ResourceManager.GetString("VveliBolsheChemVZakaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите подразделение.
        /// </summary>
        public static string VyberiteDepartment {
            get {
                return ResourceManager.GetString("VyberiteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите МОЛа самостоятельно.
        /// </summary>
        public static string VyberiteMOLaSami {
            get {
                return ResourceManager.GetString("VyberiteMOLaSami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите склад.
        /// </summary>
        public static string VyberiteStock {
            get {
                return ResourceManager.GetString("VyberiteStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус задания на производство.
        /// </summary>
        public static string VyberiteZakazNaProizvodstvo {
            get {
                return ResourceManager.GetString("VyberiteZakazNaProizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о WORK.
        /// </summary>
        public static string WorkInfo {
            get {
                return ResourceManager.GetString("WorkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа из плана .
        /// </summary>
        public static string WorkInPlan {
            get {
                return ResourceManager.GetString("WorkInPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ячейка.
        /// </summary>
        public static string Yacheika {
            get {
                return ResourceManager.GetString("Yacheika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии к работе.
        /// </summary>
        public static string YZComment {
            get {
                return ResourceManager.GetString("YZComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время завершения.
        /// </summary>
        public static string YZDateEnd {
            get {
                return ResourceManager.GetString("YZDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время начала.
        /// </summary>
        public static string YZDateStart {
            get {
                return ResourceManager.GetString("YZDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить работу.
        /// </summary>
        public static string YZEndWork {
            get {
                return ResourceManager.GetString("YZEndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник Роли.
        /// </summary>
        public static string YZRoles {
            get {
                return ResourceManager.GetString("YZRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать новую работу.
        /// </summary>
        public static string YZStartWork {
            get {
                return ResourceManager.GetString("YZStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Затраченное время.
        /// </summary>
        public static string YZTime {
            get {
                return ResourceManager.GetString("YZTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соответствие Пользователь - Подразделение.
        /// </summary>
        public static string YZUserDepartment {
            get {
                return ResourceManager.GetString("YZUserDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соответствие пользователь - Роль.
        /// </summary>
        public static string YZUserRole {
            get {
                return ResourceManager.GetString("YZUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник Сотрудники.
        /// </summary>
        public static string YZUsers {
            get {
                return ResourceManager.GetString("YZUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование работы.
        /// </summary>
        public static string YZWorkName {
            get {
                return ResourceManager.GetString("YZWorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соответствие Работа-Роль.
        /// </summary>
        public static string YZWorkRole {
            get {
                return ResourceManager.GetString("YZWorkRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник Работы.
        /// </summary>
        public static string YZWorks {
            get {
                return ResourceManager.GetString("YZWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задания на комплектовку.
        /// </summary>
        public static string ZadanieNaKomplektovku {
            get {
                return ResourceManager.GetString("ZadanieNaKomplektovku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание на пр-во.
        /// </summary>
        public static string ZadanieNaProizvodstvo {
            get {
                return ResourceManager.GetString("ZadanieNaProizvodstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание на перемещение.
        /// </summary>
        public static string ZadanieNaSklad {
            get {
                return ResourceManager.GetString("ZadanieNaSklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение задания на рабочий центр.
        /// </summary>
        public static string ZadanieNaTochku {
            get {
                return ResourceManager.GetString("ZadanieNaTochku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных пожалуйста подождите....
        /// </summary>
        public static string ZagruzkaDannih {
            get {
                return ResourceManager.GetString("ZagruzkaDannih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы поставщикам.
        /// </summary>
        public static string ZakaziPostavshikam {
            get {
                return ResourceManager.GetString("ZakaziPostavshikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ поставщику неизвестен.
        /// </summary>
        public static string ZakazNeizvesten {
            get {
                return ResourceManager.GetString("ZakazNeizvesten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ поставщику.
        /// </summary>
        public static string ZakazPostavshiku {
            get {
                return ResourceManager.GetString("ZakazPostavshiku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все желтые ячейки.
        /// </summary>
        public static string ZapolniteYellow {
            get {
                return ResourceManager.GetString("ZapolniteYellow", resourceCulture);
            }
        }
    }
}
