//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigQR
    {
        public int Id { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public bool InNZP { get; set; }
        public Nullable<int> WorkId { get; set; }
        public string QRString { get; set; }
        public System.DateTime Date { get; set; }
    }
}
