//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChasSmeni
    {
        public int Id { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minutes { get; set; }
        public int SmenaFromHour { get; set; }
        public int SmenaToHour { get; set; }
        public int SmenaFromMinute { get; set; }
        public int SmenaToMinute { get; set; }
    }
}
