//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public int Id { get; set; }
        public int DvigenieId { get; set; }
        public int Status { get; set; }
        public System.DateTime Dat { get; set; }
        public int UserId { get; set; }
        public bool DvigenieNEW { get; set; }
    
        public virtual Dvigenie Dvigenie { get; set; }
        public virtual StatusOTK StatusOTK { get; set; }
    }
}
