//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DvigenieNEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DvigenieNEW()
        {
            this.PostuplenieNaSklad = new HashSet<PostuplenieNaSklad>();
        }
    
        public int Id { get; set; }
        public decimal QTY { get; set; }
        public decimal QTYFact { get; set; }
        public int ItemID { get; set; }
        public string ItemNumber { get; set; }
        public int StockId { get; set; }
        public int StockFromId { get; set; }
        public int Lev { get; set; }
        public int FromDvigenie { get; set; }
        public string QRString { get; set; }
        public string Work { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Mnimoe { get; set; }
        public bool Otmena { get; set; }
        public int UserId { get; set; }
        public string StartFBillNo { get; set; }
        public int StartFInterId { get; set; }
        public string StockName { get; set; }
        public string StockFromName { get; set; }
        public decimal QTYInStock { get; set; }
        public decimal QTYInWork { get; set; }
        public bool EditZakazPostavshiku { get; set; }
        public string CurrentFBillNo { get; set; }
        public int CurrentFInterId { get; set; }
        public int WorkId { get; set; }
        public decimal PlanPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public int DvigenieParent { get; set; }
        public int PostavshikId { get; set; }
        public string Postavshik { get; set; }
        public string ZakazPokupatelya { get; set; }
        public string WebUserName { get; set; }
        public string KingDeeUserName { get; set; }
        public Nullable<int> BigQR { get; set; }
        public string IPAdress { get; set; }
    
        public virtual ICStockBill ICStockBill { get; set; }
        public virtual t_Item t_Item { get; set; }
        public virtual ICStockBill StartWIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostuplenieNaSklad> PostuplenieNaSklad { get; set; }
        public virtual t_Stock t_Stock { get; set; }
    }
}
