//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Base_User
    {
        public System.Guid ID { get; set; }
        public string Account { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string NTAccount { get; set; }
        public byte[] PasswordHashValue { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<bool> Built_in { get; set; }
        public Nullable<bool> SysUser { get; set; }
        public string Description { get; set; }
        public Nullable<int> PayUserID { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public string FUserName { get; set; }
        public Nullable<int> FSafeMode { get; set; }
        public string FinfoPwd { get; set; }
        public Nullable<int> IsStop { get; set; }
        public Nullable<int> IsEditPassword { get; set; }
        public Nullable<int> IsUsePeriod { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> FrequencyValue { get; set; }
        public Nullable<System.DateTime> PasswordEditDate { get; set; }
        public Nullable<System.DateTime> PasswordDeadDate { get; set; }
        public Nullable<int> MobileAuthen { get; set; }
        public byte[] MobileLoginPassword { get; set; }
        public byte[] MobileQueryPassword { get; set; }
        public Nullable<int> FIsSecurityCtrl { get; set; }
        public Nullable<int> FUserID { get; set; }
        public Nullable<System.Guid> FEmpID { get; set; }
        public Nullable<int> FLoginMustEditPWD { get; set; }
        public Nullable<System.DateTime> FLockTime { get; set; }
        public string FOpenPwd { get; set; }
        public Nullable<int> FIsAllowLoginExpired { get; set; }
    
        public virtual t_Base_User t_Base_User { get; set; }
    }
}
