//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_RefundInfoEntry
    {
        public decimal FID { get; set; }
        public int FEntryID { get; set; }
        public int FIndex { get; set; }
        public string FSiteOrderID { get; set; }
        public string FChildOrderID { get; set; }
        public Nullable<int> FItemID { get; set; }
        public Nullable<decimal> FNum { get; set; }
        public Nullable<decimal> FRefundAmount { get; set; }
        public string FRefundCode { get; set; }
        public string FRefundStatus { get; set; }
        public int FExchangeItemID { get; set; }
        public int FExchangeUnitID { get; set; }
        public decimal FExchangeQty { get; set; }
        public decimal FReceiveQty { get; set; }
        public decimal FReturnQty { get; set; }
        public Nullable<int> FRecorder { get; set; }
    }
}
