//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_RefundInfo
    {
        public decimal FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FSiteOrderID { get; set; }
        public string FChildOrderID { get; set; }
        public string FRefundCode { get; set; }
        public string FRefundStatus { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public Nullable<System.DateTime> FLastModifyDate { get; set; }
        public Nullable<bool> FIsRetrunGoods { get; set; }
        public string FRefundReason { get; set; }
        public string FRefundMemo { get; set; }
        public Nullable<decimal> FRefundAmount { get; set; }
        public Nullable<bool> FIsRefuse { get; set; }
        public Nullable<int> FItemID { get; set; }
        public Nullable<System.DateTime> FReturnDate { get; set; }
        public Nullable<decimal> FNum { get; set; }
        public string FLogisticsCompany { get; set; }
        public string FLogisticsCode { get; set; }
        public string FReturnAddress { get; set; }
        public Nullable<System.DateTime> FOutDate { get; set; }
        public string FCsStatus { get; set; }
        public string FWebShopID { get; set; }
        public string FAreaID { get; set; }
        public int FServiceType { get; set; }
        public int FServiceSource { get; set; }
        public int FServiceStatus { get; set; }
        public int FServiceCategory { get; set; }
        public int FEntryID { get; set; }
        public string FOrderID { get; set; }
        public string FBuyerNick { get; set; }
        public string FItemName { get; set; }
        public string FBuyerAccount { get; set; }
        public int FExchangeItemID { get; set; }
        public int FExchangeUnitID { get; set; }
        public decimal FExchangeQty { get; set; }
        public decimal FReceiveQty { get; set; }
        public decimal FReturnQty { get; set; }
        public Nullable<int> FRecorder { get; set; }
        public Nullable<bool> FIsFastRefund { get; set; }
        public string FTagList { get; set; }
        public int FAdvanceStatus { get; set; }
        public int FVoucherID { get; set; }
    }
}
