//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_ReceiptEntry
    {
        public int FID { get; set; }
        public int FEntryID { get; set; }
        public int FIndex { get; set; }
        public int FID_SRC { get; set; }
        public int FEntryID_SRC { get; set; }
        public int FClassID_SRC { get; set; }
        public string FBillNO_SRC { get; set; }
        public int FItemID { get; set; }
        public Nullable<int> FAttrCode { get; set; }
        public string FNumID { get; set; }
        public int FUnitID { get; set; }
        public decimal FPrice { get; set; }
        public decimal FQty { get; set; }
        public decimal FAmount { get; set; }
        public decimal FDiscountFee { get; set; }
        public decimal FFreight { get; set; }
        public int FMealID { get; set; }
        public string FIsFree { get; set; }
        public string FSiteOrderID { get; set; }
        public int FSignStatus { get; set; }
        public int FStockID { get; set; }
        public int FReturnStock { get; set; }
        public decimal FReturnQty { get; set; }
        public decimal FExchangeQty { get; set; }
        public string FReturnNO { get; set; }
        public Nullable<int> FReturnID { get; set; }
        public string FBackNO { get; set; }
        public Nullable<int> FBackID { get; set; }
        public string FExchangeNO { get; set; }
        public Nullable<int> FExchangeID { get; set; }
        public Nullable<System.DateTime> FReceiptDate { get; set; }
        public Nullable<System.DateTime> FRetrunDate { get; set; }
        public Nullable<System.DateTime> FExchangeDate { get; set; }
        public int FRowClosed { get; set; }
        public int FDisposeType { get; set; }
        public Nullable<decimal> FRefundFID { get; set; }
    }
}
