//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_StockPlanDetail
    {
        public int FIndex { get; set; }
        public int FItemID { get; set; }
        public Nullable<System.DateTime> FNeedDate { get; set; }
        public Nullable<int> FSourceTranType { get; set; }
        public Nullable<int> FSourceInterID { get; set; }
        public Nullable<int> FSourceEntryID { get; set; }
        public Nullable<int> FRelationTranType { get; set; }
        public Nullable<int> FRelationInterID { get; set; }
        public Nullable<int> FRelationEntryID { get; set; }
        public Nullable<int> FParentTranType { get; set; }
        public Nullable<int> FParentInterID { get; set; }
        public Nullable<int> FParentEntryID { get; set; }
        public Nullable<decimal> FBeginStockQty { get; set; }
        public Nullable<decimal> FNeedQty { get; set; }
        public Nullable<decimal> FWillOutQty { get; set; }
        public Nullable<decimal> FWillInQty { get; set; }
        public Nullable<decimal> FKillQty { get; set; }
        public Nullable<decimal> FFactNeedQty { get; set; }
        public Nullable<decimal> FPlanOrderQty { get; set; }
        public Nullable<decimal> FWillStockQty { get; set; }
        public Nullable<int> FPlanOrderInterID { get; set; }
        public Nullable<int> FBomInterID { get; set; }
        public Nullable<short> FBillType { get; set; }
        public Nullable<int> FOrderIndex { get; set; }
        public int FCurPeriod { get; set; }
        public int FCalOrder { get; set; }
        public Nullable<short> FISOldData { get; set; }
        public int FAdjustID { get; set; }
        public int FSuggestCancel { get; set; }
        public int FAdjustEndDays { get; set; }
        public int FAdjustBeginDays { get; set; }
        public int FMRPLockFlag { get; set; }
        public decimal FMRPLockQty { get; set; }
        public decimal FQty_In_Plan { get; set; }
        public decimal FQty_In_OnDo { get; set; }
        public decimal FQty_In_Prep { get; set; }
        public decimal FQty_In_Repl { get; set; }
        public decimal FQty_Out_Delay { get; set; }
        public decimal FQty_Out_Plan { get; set; }
        public decimal FQty_Out_Task { get; set; }
        public decimal FQty_Out_Repl { get; set; }
        public decimal FQty_Out_Lock { get; set; }
        public decimal FQty_Req_Fore { get; set; }
        public decimal FQty_Req_Sale { get; set; }
        public decimal FQty_Req_Inv { get; set; }
        public decimal FQty_Req_Rela { get; set; }
        public decimal FQty_REQ_Lock { get; set; }
        public decimal FQty_Inv_Use { get; set; }
        public decimal FQty_Inv_Lock { get; set; }
        public int FAdjustSplitID { get; set; }
        public Nullable<System.DateTime> FOrgNeedDate { get; set; }
        public int FRunID { get; set; }
        public Nullable<System.DateTime> FBeginDate { get; set; }
        public int FDayID { get; set; }
        public short FSourceType { get; set; }
        public int FBOMCategory { get; set; }
        public int FOrderBOMInterID { get; set; }
        public int FSupplyID { get; set; }
        public int FSubstitute { get; set; }
        public int FBatchSplitOrder { get; set; }
        public int FAuxPropID { get; set; }
        public string FMTONo { get; set; }
    }
}
