//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IC_StockMatching
    {
        public string FGuanyiStockNumber { get; set; }
        public string FGuanyiStockName { get; set; }
        public string FGuanyiStockArea { get; set; }
        public int FStockID { get; set; }
        public int FSPID { get; set; }
        public Nullable<byte> FIsUploadStock { get; set; }
        public string FGuanyiSPNumber { get; set; }
        public string FGuanyiSPName { get; set; }
    }
}
