//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICBal
    {
        public string FBrNo { get; set; }
        public int FYear { get; set; }
        public short FPeriod { get; set; }
        public int FItemID { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<decimal> FBegQty { get; set; }
        public Nullable<decimal> FReceive { get; set; }
        public Nullable<decimal> FSend { get; set; }
        public Nullable<decimal> FYtdReceive { get; set; }
        public Nullable<decimal> FYtdSend { get; set; }
        public Nullable<decimal> FEndQty { get; set; }
        public decimal FBegBal { get; set; }
        public decimal FDebit { get; set; }
        public decimal FCredit { get; set; }
        public decimal FYtdDebit { get; set; }
        public decimal FYtdCredit { get; set; }
        public decimal FEndBal { get; set; }
        public decimal FBegDiff { get; set; }
        public decimal FReceiveDiff { get; set; }
        public decimal FSendDiff { get; set; }
        public decimal FEndDiff { get; set; }
        public int FBillInterID { get; set; }
        public int FEntryID { get; set; }
        public int FStockGroupID { get; set; }
        public decimal FYtdReceiveDiff { get; set; }
        public decimal FYtdSendDiff { get; set; }
        public decimal FSecBegQty { get; set; }
        public decimal FSecReceive { get; set; }
        public decimal FSecSend { get; set; }
        public decimal FSecYtdReceive { get; set; }
        public decimal FSecYtdSend { get; set; }
        public decimal FSecEndQty { get; set; }
        public string FStockInDate { get; set; }
        public int FAuxPropID { get; set; }
        public Nullable<int> FCheck { get; set; }
        public int FStockID { get; set; }
    }
}
