//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICBillAction
    {
        public int FID { get; set; }
        public int FTransType { get; set; }
        public int FPage { get; set; }
        public int FOrder { get; set; }
        public string FFieldName { get; set; }
        public string FRelationID { get; set; }
        public string FAction { get; set; }
        public short FFuncID { get; set; }
        public int FClassActionID { get; set; }
    }
}
