//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICBOMChild
    {
        public string FBrNo { get; set; }
        public int FEntryID { get; set; }
        public int FInterID { get; set; }
        public int FItemID { get; set; }
        public decimal FAuxQty { get; set; }
        public decimal FQty { get; set; }
        public decimal FScrap { get; set; }
        public int FOperSN { get; set; }
        public int FOperID { get; set; }
        public string FMachinePos { get; set; }
        public string FNote { get; set; }
        public int FMaterielType { get; set; }
        public int FMarshalType { get; set; }
        public decimal FPercent { get; set; }
        public System.DateTime FBeginDay { get; set; }
        public System.DateTime FEndDay { get; set; }
        public decimal FOffSetDay { get; set; }
        public int FBackFlush { get; set; }
        public Nullable<int> FStockID { get; set; }
        public int FSPID { get; set; }
        public short FSupply { get; set; }
        public int FUnitID { get; set; }
        public int FAuxPropID { get; set; }
        public Nullable<System.DateTime> FPDMImportDate { get; set; }
        public string FPositionNo { get; set; }
        public string FItemSize { get; set; }
        public string FItemSuite { get; set; }
        public string FNote1 { get; set; }
        public string FNote2 { get; set; }
        public string FNote3 { get; set; }
        public Nullable<short> FHasChar { get; set; }
        public System.Guid FDetailID { get; set; }
        public int FEntryKey { get; set; }
        public Nullable<decimal> FCostPercentage { get; set; }
        public string FEntrySelfZ0143 { get; set; }
        public string FEntrySelfZ0144 { get; set; }
        public Nullable<int> FEntrySelfZ0146 { get; set; }
        public string FEntrySelfZ0150 { get; set; }
        public int FOutSourceTranType { get; set; }
        public int FOutSourceInterID { get; set; }
        public int FOutSourceEntryID { get; set; }
    
        public virtual ICBOM ICBOM { get; set; }
        public virtual t_Item t_Item { get; set; }
    }
}
