//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICBOMGroup
    {
        public int FInterID { get; set; }
        public int FParentID { get; set; }
        public string FName { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> FBootID { get; set; }
    }
}
