//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICInvInitial
    {
        public string FBrNo { get; set; }
        public short FPeriod { get; set; }
        public int FStockID { get; set; }
        public int FItemID { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<decimal> FBegQty { get; set; }
        public Nullable<decimal> FReceive { get; set; }
        public Nullable<decimal> FSend { get; set; }
        public Nullable<decimal> FYtdReceive { get; set; }
        public Nullable<decimal> FYtdSend { get; set; }
        public Nullable<decimal> FEndQty { get; set; }
        public decimal FBegBal { get; set; }
        public decimal FDebit { get; set; }
        public decimal FCredit { get; set; }
        public decimal FYtdDebit { get; set; }
        public decimal FYtdCredit { get; set; }
        public decimal FEndBal { get; set; }
        public decimal FBegDiff { get; set; }
        public decimal FReceiveDiff { get; set; }
        public decimal FSendDiff { get; set; }
        public int FBillInterID { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxBegQty { get; set; }
        public decimal FYtdBegQty { get; set; }
        public decimal FYtdAuxBegQty { get; set; }
        public decimal FYtdAuxReceive { get; set; }
        public decimal FYtdAuxSend { get; set; }
        public decimal FYtdBegBal { get; set; }
        public decimal FYtdBegDiff { get; set; }
        public decimal FYtdReceiveDiff { get; set; }
        public decimal FYtdSendDiff { get; set; }
        public string FKFDate { get; set; }
        public decimal FKFPeriod { get; set; }
        public int FSPID { get; set; }
        public decimal FSecBegQty { get; set; }
        public decimal FSecReceive { get; set; }
        public decimal FSecSend { get; set; }
        public decimal FSecYtdReceive { get; set; }
        public decimal FSecYtdSend { get; set; }
        public decimal FSecEndQty { get; set; }
        public int FSecUnitID { get; set; }
        public string FStockInDate { get; set; }
        public int FAuxPropID { get; set; }
        public decimal FSecCoefficient { get; set; }
        public decimal FAuxUnitBegQty { get; set; }
        public decimal FYtdAuxUnitBegQty { get; set; }
        public decimal FYtdAuxUnitSend { get; set; }
        public decimal FYtdAuxUnitReceive { get; set; }
        public int FSNListID { get; set; }
        public string FMTONo { get; set; }
        public int FSupplyID { get; set; }
        public Nullable<System.DateTime> FPeriodDate { get; set; }
    }
}
