//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICInventoryInLogs
    {
        public int FInterID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public int FBillerID { get; set; }
        public int FCheckerID { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public int FCollector { get; set; }
        public string FMultiCheckStatus { get; set; }
    }
}
