//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICMOChangeEntry
    {
        public int FEntryID { get; set; }
        public int FID { get; set; }
        public int FIndex { get; set; }
        public int FICMOInterID { get; set; }
        public string FICMOBillNo { get; set; }
        public int FOrderInterID { get; set; }
        public string FOrderBillNo { get; set; }
        public int FItemID { get; set; }
        public int FUnitID { get; set; }
        public int FBOMInterID { get; set; }
        public int FRoutingID { get; set; }
        public int FWorkType { get; set; }
        public decimal FAuxQtyPlan { get; set; }
        public decimal FQtyPlan { get; set; }
        public int FWorkShop { get; set; }
        public int FCostObjID { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<System.DateTime> FPlanCommitDate { get; set; }
        public Nullable<System.DateTime> FPlanFinishDate { get; set; }
        public decimal FInHighLimit { get; set; }
        public decimal FInLowLimit { get; set; }
        public decimal FInHighLimitQty { get; set; }
        public decimal FInLowLimitQty { get; set; }
        public Nullable<System.DateTime> FChangeDate { get; set; }
        public int FChanger { get; set; }
        public string FChangeReason { get; set; }
        public string FNote { get; set; }
        public int FChangeFlag { get; set; }
        public int FCustID { get; set; }
        public int FClassID_SRC { get; set; }
        public int FPlanCategory { get; set; }
        public int FBomCategory { get; set; }
        public int FAuxPropID { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
    }
}
