//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICMOConvertBill
    {
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public string FCheckFlag { get; set; }
        public int FICMOInterID { get; set; }
        public string FConvertType { get; set; }
        public int FBillerID { get; set; }
        public Nullable<System.DateTime> FBillDate { get; set; }
        public int FOldUnitID { get; set; }
        public decimal FAuxOldPlanQty { get; set; }
        public decimal FAuxNewPlanQty { get; set; }
        public decimal FOldPlanQty { get; set; }
        public decimal FNewPlanQty { get; set; }
        public int FCheckerID { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public int FItemID { get; set; }
        public int FOldType { get; set; }
        public string FICMOBillNo { get; set; }
        public int FOldCostID { get; set; }
        public int FClassID_SRC { get; set; }
        public int FAuxPropID { get; set; }
    }
}
