//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICStockBillEntry
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public int FEntryID { get; set; }
        public Nullable<int> FItemID { get; set; }
        public decimal FQtyMust { get; set; }
        public decimal FQty { get; set; }
        public decimal FPrice { get; set; }
        public string FBatchNo { get; set; }
        public decimal FAmount { get; set; }
        public string FNote { get; set; }
        public Nullable<int> FSCBillInterID { get; set; }
        public string FSCBillNo { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxPrice { get; set; }
        public decimal FAuxQty { get; set; }
        public decimal FAuxQtyMust { get; set; }
        public decimal FQtyActual { get; set; }
        public decimal FAuxQtyActual { get; set; }
        public decimal FPlanPrice { get; set; }
        public decimal FAuxPlanPrice { get; set; }
        public int FSourceEntryID { get; set; }
        public decimal FCommitQty { get; set; }
        public decimal FAuxCommitQty { get; set; }
        public Nullable<System.DateTime> FKFDate { get; set; }
        public int FKFPeriod { get; set; }
        public Nullable<int> FDCSPID { get; set; }
        public Nullable<int> FSCSPID { get; set; }
        public decimal FConsignPrice { get; set; }
        public decimal FConsignAmount { get; set; }
        public decimal FProcessCost { get; set; }
        public decimal FMaterialCost { get; set; }
        public decimal FTaxAmount { get; set; }
        public string FMapNumber { get; set; }
        public string FMapName { get; set; }
        public int FOrgBillEntryID { get; set; }
        public Nullable<int> FOperID { get; set; }
        public decimal FPlanAmount { get; set; }
        public decimal FProcessPrice { get; set; }
        public decimal FTaxRate { get; set; }
        public Nullable<int> FSnListID { get; set; }
        public decimal FAmtRef { get; set; }
        public int FAuxPropID { get; set; }
        public decimal FCost { get; set; }
        public decimal FPriceRef { get; set; }
        public decimal FAuxPriceRef { get; set; }
        public Nullable<System.DateTime> FFetchDate { get; set; }
        public decimal FQtyInvoice { get; set; }
        public decimal FQtyInvoiceBase { get; set; }
        public decimal FUnitCost { get; set; }
        public decimal FSecCoefficient { get; set; }
        public decimal FSecQty { get; set; }
        public decimal FSecCommitQty { get; set; }
        public int FSourceTranType { get; set; }
        public int FSourceInterId { get; set; }
        public string FSourceBillNo { get; set; }
        public int FContractInterID { get; set; }
        public int FContractEntryID { get; set; }
        public string FContractBillNo { get; set; }
        public string FICMOBillNo { get; set; }
        public int FICMOInterID { get; set; }
        public int FPPBomEntryID { get; set; }
        public int FOrderInterID { get; set; }
        public int FOrderEntryID { get; set; }
        public string FOrderBillNo { get; set; }
        public decimal FAllHookQTY { get; set; }
        public decimal FAllHookAmount { get; set; }
        public decimal FCurrentHookQTY { get; set; }
        public decimal FCurrentHookAmount { get; set; }
        public decimal FStdAllHookAmount { get; set; }
        public decimal FStdCurrentHookAmount { get; set; }
        public int FSCStockID { get; set; }
        public int FDCStockID { get; set; }
        public Nullable<System.DateTime> FPeriodDate { get; set; }
        public int FCostObjGroupID { get; set; }
        public int FCostOBJID { get; set; }
        public int FDetailID { get; set; }
        public decimal FMaterialCostPrice { get; set; }
        public int FReProduceType { get; set; }
        public int FBomInterID { get; set; }
        public decimal FDiscountRate { get; set; }
        public decimal FDiscountAmount { get; set; }
        public int FSepcialSaleId { get; set; }
        public decimal FOutCommitQty { get; set; }
        public decimal FOutSecCommitQty { get; set; }
        public decimal FDBCommitQty { get; set; }
        public decimal FDBSecCommitQty { get; set; }
        public decimal FAuxQtyInvoice { get; set; }
        public int FOperSN { get; set; }
        public short FCheckStatus { get; set; }
        public Nullable<decimal> FSplitSecQty { get; set; }
        public int FInStockID { get; set; }
        public decimal FSaleCommitQty { get; set; }
        public decimal FSaleSecCommitQty { get; set; }
        public decimal FSaleAuxCommitQty { get; set; }
        public int FSelectedProcID { get; set; }
        public decimal FVWInStockQty { get; set; }
        public decimal FAuxVWInStockQty { get; set; }
        public decimal FSecVWInStockQty { get; set; }
        public decimal FSecInvoiceQty { get; set; }
        public int FCostCenterID { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public decimal FSecQtyActual { get; set; }
        public decimal FSecQtyMust { get; set; }
        public string FClientOrderNo { get; set; }
        public Nullable<int> FClientEntryID { get; set; }
        public byte FRowClosed { get; set; }
        public Nullable<decimal> FCostPercentage { get; set; }
        public string FItemSize { get; set; }
        public string FItemSuite { get; set; }
        public string FPositionNo { get; set; }
        public Nullable<byte> FAcctCheck { get; set; }
        public Nullable<byte> FClosing { get; set; }
        public Nullable<int> FDeliveryNoticeEntryID { get; set; }
        public Nullable<int> FDeliveryNoticeFID { get; set; }
        public int FIsVMI { get; set; }
        public int FEntrySupply { get; set; }
        public int FChkPassItem { get; set; }
        public int FSEOutInterID { get; set; }
        public int FSEOutEntryID { get; set; }
        public string FSEOutBillNo { get; set; }
        public string FConfirmMemEntry { get; set; }
        public decimal FWebReturnQty { get; set; }
        public decimal FWebReturnAuxQty { get; set; }
        public string FItemStatementBillNO { get; set; }
        public int FItemStatementEntryID { get; set; }
        public int FItemStatementInterID { get; set; }
        public Nullable<decimal> FCommitAmt { get; set; }
        public Nullable<int> FFatherProductID { get; set; }
        public decimal FRealAmount { get; set; }
        public decimal FRealPrice { get; set; }
        public decimal FDefaultBaseQty { get; set; }
        public decimal FDefaultQty { get; set; }
        public decimal FRealStockBaseQty { get; set; }
        public decimal FRealStockQty { get; set; }
        public int FDiscardID { get; set; }
        public string FOLOrderBillNo { get; set; }
        public int FLockFlag { get; set; }
        public string FEntrySelfB0168 { get; set; }
        public string FEntrySelfB0169 { get; set; }
        public string FEntrySelfB0857 { get; set; }
        public string FEntrySelfA0159 { get; set; }
        public string FEntrySelfA0557 { get; set; }
        public Nullable<decimal> FEntrySelfB0456 { get; set; }
        public string FEntrySelfB0457 { get; set; }
        public string FEntrySelfB0458 { get; set; }
        public string FEntrySelfA0160 { get; set; }
        public string FEntrySelfB0459 { get; set; }
        public string FEntrySelfB0858 { get; set; }
        public string FEntrySelfA0558 { get; set; }
        public Nullable<decimal> FEntrySelfB0460 { get; set; }
        public string FEntrySelfA0240 { get; set; }
        public Nullable<decimal> FEntrySelfA0161 { get; set; }
        public string FReturnNoticeBillNO { get; set; }
        public int FReturnNoticeEntryID { get; set; }
        public int FReturnNoticeInterID { get; set; }
        public decimal FProductFileQty { get; set; }
        public string FServiceRequestNo { get; set; }
        public string FSplitState { get; set; }
        public decimal FQtySplit { get; set; }
        public decimal FAuxQtySplit { get; set; }
        public decimal FAddQty { get; set; }
        public decimal FAuxAddQty { get; set; }
        public Nullable<decimal> FPurchasePrice { get; set; }
        public Nullable<decimal> FPurchaseAmount { get; set; }
        public Nullable<decimal> FCheckAmount { get; set; }
        public int FOutSourceInterID { get; set; }
        public int FOutSourceEntryID { get; set; }
        public int FOutSourceTranType { get; set; }
        public Nullable<decimal> FProcessTaxPrice { get; set; }
        public Nullable<decimal> FProcessTaxCost { get; set; }
        public string FShopName { get; set; }
        public Nullable<decimal> FPostFee { get; set; }
        public Nullable<decimal> FReviewBillsQty { get; set; }
        public decimal FPTLQty { get; set; }
        public int FBarCodeListID { get; set; }
        public int FEntryAccessoryCount { get; set; }
        public Nullable<decimal> FAUXQTY_Gain { get; set; }
        public Nullable<decimal> FAUXQTY_Loss { get; set; }
        public bool FNeedBackFlush { get; set; }
        public int FBackFlushFlag { get; set; }
        public int FSendPlanID { get; set; }
        public string FEntrySelfA0173 { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        public virtual ICStockBill ICStockBill { get; set; }
        public virtual POOrder POOrder { get; set; }
        public virtual t_Stock t_StockTo { get; set; }
    }
}
