//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICSubContractEntry
    {
        public int FInterID { get; set; }
        public int FEntryID { get; set; }
        public int FIndex { get; set; }
        public int FDetailID { get; set; }
        public int FItemID { get; set; }
        public int FMapID { get; set; }
        public string FMapName { get; set; }
        public int FAuxPropID { get; set; }
        public decimal FSecQty { get; set; }
        public decimal FSecCommitQty { get; set; }
        public decimal FSecCoefficient { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxQty { get; set; }
        public decimal FQty { get; set; }
        public decimal FAuxPrice { get; set; }
        public decimal FAuxTaxPrice { get; set; }
        public decimal FAmount { get; set; }
        public decimal FDiscountRate { get; set; }
        public decimal FAuxPriceDiscount { get; set; }
        public decimal FAmtDiscount { get; set; }
        public decimal FTaxRate { get; set; }
        public decimal FTaxAmount { get; set; }
        public decimal FAllAmount { get; set; }
        public decimal FStdAllAmount { get; set; }
        public Nullable<System.DateTime> FPayShipDate { get; set; }
        public System.DateTime FFetchDate { get; set; }
        public int FBOMInterID { get; set; }
        public decimal FInHighLimit { get; set; }
        public decimal FInLowLimit { get; set; }
        public string FNote { get; set; }
        public byte FMrpAutoClosed { get; set; }
        public byte FMrpClosed { get; set; }
        public byte FMRPLockFlag { get; set; }
        public int FClassTypeID_SRC { get; set; }
        public int FEntryID_SRC { get; set; }
        public int FInterID_SRC { get; set; }
        public string FBillNo_SRC { get; set; }
        public int FInterIDOrder_SRC { get; set; }
        public int FEntryIDOrder_SRC { get; set; }
        public string FOrderNo { get; set; }
        public decimal FInHighLimitQty { get; set; }
        public decimal FInLowLimitQty { get; set; }
        public decimal FAuxCommitQty { get; set; }
        public decimal FCommitQty { get; set; }
        public decimal FAuxStockQty { get; set; }
        public decimal FStockQty { get; set; }
        public decimal FAuxQtyInvoice { get; set; }
        public decimal FQtyInvoice { get; set; }
        public decimal FReceiveAmountFor_Commit { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public byte FMrpTrackFlag { get; set; }
        public int FPORInterID { get; set; }
        public string FPORNumber { get; set; }
        public decimal FBCommitQty { get; set; }
        public decimal FAuxBCommitQty { get; set; }
        public decimal FSecQtyInvoice { get; set; }
        public decimal FSecBCommitQty { get; set; }
        public decimal FSecStockQty { get; set; }
        public int FBOMCategory { get; set; }
        public string FSupConfirm { get; set; }
        public Nullable<System.DateTime> FSupConDate { get; set; }
        public Nullable<decimal> FSupConQty { get; set; }
        public string FSupConMem { get; set; }
        public Nullable<System.DateTime> FSupConFetchDate { get; set; }
        public Nullable<int> FSupConfirmor { get; set; }
        public string FRejectRefuseNote { get; set; }
        public string FRefuseNote { get; set; }
        public int FEntryAccessoryCount { get; set; }
        public decimal FAuxDeliveryQty { get; set; }
        public decimal FDeliveryQty { get; set; }
        public int FQualityRptBillID { get; set; }
        public Nullable<decimal> FAuxReceiptQty { get; set; }
        public Nullable<decimal> FReceiptQty { get; set; }
        public Nullable<decimal> FAuxReturnQty { get; set; }
        public Nullable<decimal> FReturnQty { get; set; }
        public int FCheckMethod { get; set; }
        public int FIsCheck { get; set; }
        public decimal FPayApplyAmountFor_Commit { get; set; }
        public Nullable<decimal> FCommitAmt { get; set; }
        public Nullable<decimal> FCommitAmtTax { get; set; }
        public Nullable<decimal> FCommitStdAmtInTax { get; set; }
        public Nullable<decimal> FCommitTax { get; set; }
        public Nullable<decimal> FStockQtyOnlyForShow { get; set; }
        public decimal FPayReqPayAmountFor { get; set; }
        public decimal FPrice { get; set; }
        public int FOrderBOMEntryID { get; set; }
        public int FOutSourceInterID { get; set; }
        public int FOutSourceEntryID { get; set; }
        public int FOutSourceTranType { get; set; }
    
        public virtual ICSubContract ICSubContract { get; set; }
        public virtual t_Item t_Item { get; set; }
    }
}
