//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICTemplate
    {
        public string FID { get; set; }
        public int FCtlIndex { get; set; }
        public int FTabIndex { get; set; }
        public string FCaption { get; set; }
        public short FCtlType { get; set; }
        public int FLookUpCls { get; set; }
        public bool FNeedSave { get; set; }
        public short FValueType { get; set; }
        public short FSaveValue { get; set; }
        public string FFieldName { get; set; }
        public int FLeft { get; set; }
        public int FTop { get; set; }
        public int FWidth { get; set; }
        public int FHeight { get; set; }
        public int FEnable { get; set; }
        public bool FPrint { get; set; }
        public string FFontName { get; set; }
        public short FFontSize { get; set; }
        public Nullable<int> FSelBill { get; set; }
        public bool FMustInput { get; set; }
        public string FFilter { get; set; }
        public string FRelationID { get; set; }
        public string FAction { get; set; }
        public bool FLockA { get; set; }
        public int FROB { get; set; }
        public bool FDefaultCtl { get; set; }
        public int FVisForBillType { get; set; }
        public string FVBACtlType { get; set; }
        public bool FRelateOutTbl { get; set; }
        public bool FSysMustInputItem { get; set; }
        public string FCaption_CHT { get; set; }
        public string FCaption_EN { get; set; }
        public bool FInEntryForSPrint { get; set; }
        public int FRMustInput { get; set; }
        public short FIsVisibleForList { get; set; }
        public bool FCanEditedAllTime { get; set; }
        public short FAllowCopy { get; set; }
        public string FDefaultValue { get; set; }
        public string FMaxValue { get; set; }
        public string FMinValue { get; set; }
        public string FFormat { get; set; }
        public int FLookUpType { get; set; }
        public int FOptionExt { get; set; }
        public int FItemClassID { get; set; }
        public int FUserDefineClassID { get; set; }
        public string FDescription { get; set; }
        public string FDescription_CHT { get; set; }
        public string FDescription_EN { get; set; }
        public int IsSupportImport { get; set; }
        public Nullable<int> FLeftForBarCode { get; set; }
        public Nullable<int> FTopForBarCode { get; set; }
        public Nullable<int> FWidthForBarCode { get; set; }
        public Nullable<int> FHeightForBarCode { get; set; }
        public bool FCanEditedCheck { get; set; }
    }
}
