//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICWork
    {
        public string FBrNo { get; set; }
        public int FItemID { get; set; }
        public string FID { get; set; }
        public int FParentID { get; set; }
        public string FName { get; set; }
        public Nullable<int> FBOMID { get; set; }
        public Nullable<decimal> FQty { get; set; }
        public Nullable<System.DateTime> FStartDate { get; set; }
        public Nullable<System.DateTime> FEndDate { get; set; }
        public string FNote { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<int> FOperID { get; set; }
        public Nullable<System.DateTime> FOperDate { get; set; }
    }
}
