//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoWorks
    {
        public int Id { get; set; }
        public string WorkName { get; set; }
        public string ItemNumber { get; set; }
        public int ItemId { get; set; }
        public string FBillNo { get; set; }
        public decimal QTY { get; set; }
        public decimal FQtyMust { get; set; }
        public decimal FQty { get; set; }
        public decimal FStockQty { get; set; }
        public decimal FQtySupply { get; set; }
        public decimal FWipQty { get; set; }
        public decimal FQtyPick { get; set; }
        public int WebUserId { get; set; }
        public string WebUserName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string IPAdress { get; set; }
    }
}
