//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventSecondQR
    {
        public int Id { get; set; }
        public int StockID { get; set; }
        public int ItemId { get; set; }
        public int QRId { get; set; }
        public decimal QTY { get; set; }
        public int VedomostId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int UserId { get; set; }
    
        public virtual UsersKDW UsersKDW { get; set; }
        public virtual QRTable QRTable { get; set; }
    }
}
