//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komplekt
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int POOrderId { get; set; }
        public int DvigenieCIN { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        public virtual Dvigenie Dvigenie { get; set; }
        public virtual POOrder POOrder { get; set; }
    }
}
