//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastDvigs
    {
        public Nullable<int> DvigenieId { get; set; }
        public Nullable<int> QRId { get; set; }
        public int ItemID { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        public virtual t_ICItemMaterial t_ICItemMaterial { get; set; }
        public virtual QRTable QRTable { get; set; }
        public virtual Dvigenie Dvigenie { get; set; }
    }
}
