//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KingDeeDB : DbContext
    {
        public KingDeeDB()
            : base("name=KingDeeDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IC_Receipt> IC_Receipt { get; set; }
        public virtual DbSet<IC_ReceiptEntry> IC_ReceiptEntry { get; set; }
        public virtual DbSet<IC_RefundInfo> IC_RefundInfo { get; set; }
        public virtual DbSet<IC_RefundInfoEntry> IC_RefundInfoEntry { get; set; }
        public virtual DbSet<IC_Refunds> IC_Refunds { get; set; }
        public virtual DbSet<IC_StockMatching> IC_StockMatching { get; set; }
        public virtual DbSet<IC_StockPlanDetail> IC_StockPlanDetail { get; set; }
        public virtual DbSet<ICBal> ICBal { get; set; }
        public virtual DbSet<ICBillAction> ICBillAction { get; set; }
        public virtual DbSet<ICBillNo> ICBillNo { get; set; }
        public virtual DbSet<ICBOM> ICBOM { get; set; }
        public virtual DbSet<ICBOMChild> ICBOMChild { get; set; }
        public virtual DbSet<ICBOMGroup> ICBOMGroup { get; set; }
        public virtual DbSet<ICInvBal> ICInvBal { get; set; }
        public virtual DbSet<ICInventory> ICInventory { get; set; }
        public virtual DbSet<ICInventoryInLogs> ICInventoryInLogs { get; set; }
        public virtual DbSet<ICInvInitial> ICInvInitial { get; set; }
        public virtual DbSet<ICInvLog> ICInvLog { get; set; }
        public virtual DbSet<ICInvLogBal> ICInvLogBal { get; set; }
        public virtual DbSet<ICMO> ICMO { get; set; }
        public virtual DbSet<ICMOChange> ICMOChange { get; set; }
        public virtual DbSet<ICMOChangeEntry> ICMOChangeEntry { get; set; }
        public virtual DbSet<ICMOConvertBill> ICMOConvertBill { get; set; }
        public virtual DbSet<ICMOConvertBillEntry> ICMOConvertBillEntry { get; set; }
        public virtual DbSet<ICStockBill> ICStockBill { get; set; }
        public virtual DbSet<ICStockBillEntry> ICStockBillEntry { get; set; }
        public virtual DbSet<ICTemplate> ICTemplate { get; set; }
        public virtual DbSet<ICWork> ICWork { get; set; }
        public virtual DbSet<POInStock> POInStock { get; set; }
        public virtual DbSet<POInvBal> POInvBal { get; set; }
        public virtual DbSet<POInventory> POInventory { get; set; }
        public virtual DbSet<POOrder> POOrder { get; set; }
        public virtual DbSet<POOrderEntry> POOrderEntry { get; set; }
        public virtual DbSet<PORequest> PORequest { get; set; }
        public virtual DbSet<POStockBillEntry> POStockBillEntry { get; set; }
        public virtual DbSet<PPBOM> PPBOM { get; set; }
        public virtual DbSet<PPBomChange> PPBomChange { get; set; }
        public virtual DbSet<PPBomChangeEntry> PPBomChangeEntry { get; set; }
        public virtual DbSet<PPBOMEntry> PPBOMEntry { get; set; }
        public virtual DbSet<PPOrder> PPOrder { get; set; }
        public virtual DbSet<PPOrderEntry> PPOrderEntry { get; set; }
        public virtual DbSet<t_Base_Emp> t_Base_Emp { get; set; }
        public virtual DbSet<t_Department> t_Department { get; set; }
        public virtual DbSet<t_Fee> t_Fee { get; set; }
        public virtual DbSet<t_Item> t_Item { get; set; }
        public virtual DbSet<t_Stock> t_Stock { get; set; }
        public virtual DbSet<t_StockPlace> t_StockPlace { get; set; }
        public virtual DbSet<t_StockPlaceGroup> t_StockPlaceGroup { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<ZPStockBillEntry> ZPStockBillEntry { get; set; }
        public virtual DbSet<ICStock_Inv> ICStock_Inv { get; set; }
        public virtual DbSet<t_Supplier> t_Supplier { get; set; }
        public virtual DbSet<t_Supply> t_Supply { get; set; }
        public virtual DbSet<t_SupplyEntry> t_SupplyEntry { get; set; }
        public virtual DbSet<QRTable> QRTable { get; set; }
        public virtual DbSet<ICMaxNum> ICMaxNum { get; set; }
        public virtual DbSet<NomenklaturaEnterprise> NomenklaturaEnterprise { get; set; }
        public virtual DbSet<StocksMOL> StocksMOL { get; set; }
        public virtual DbSet<StocksRusKit> StocksRusKit { get; set; }
        public virtual DbSet<Dvigenie> Dvigenie { get; set; }
        public virtual DbSet<DepartmentsToUsers> DepartmentsToUsers { get; set; }
        public virtual DbSet<ICPlan_PMCDetail> ICPlan_PMCDetail { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<KingDeeWebRoles> KingDeeWebRoles { get; set; }
        public virtual DbSet<WebRoles> WebRoles { get; set; }
        public virtual DbSet<ComputerNames> ComputerNames { get; set; }
        public virtual DbSet<PlanoviWorks> PlanoviWorks { get; set; }
        public virtual DbSet<StarMehWorks> StarMehWorks { get; set; }
        public virtual DbSet<OcheredWorks> OcheredWorks { get; set; }
        public virtual DbSet<HR_Base_User> HR_Base_User { get; set; }
        public virtual DbSet<t_Base_User> t_Base_User { get; set; }
        public virtual DbSet<UsersKDW> UsersKDW { get; set; }
        public virtual DbSet<DepartmentToLine> DepartmentToLine { get; set; }
        public virtual DbSet<MolsOfDepartments> MolsOfDepartments { get; set; }
        public virtual DbSet<NZP> NZP { get; set; }
        public virtual DbSet<Komplekt> Komplekt { get; set; }
        public virtual DbSet<Planogramma> Planogramma { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Yacheika> Yacheika { get; set; }
        public virtual DbSet<NomenklaturaPlace> NomenklaturaPlace { get; set; }
        public virtual DbSet<Control> Control { get; set; }
        public virtual DbSet<StatusOTK> StatusOTK { get; set; }
        public virtual DbSet<ICSubContract> ICSubContract { get; set; }
        public virtual DbSet<ICSubContractEntry> ICSubContractEntry { get; set; }
        public virtual DbSet<DepartmentToStocks> DepartmentToStocks { get; set; }
        public virtual DbSet<t_User> t_User { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<StockPriem> StockPriem { get; set; }
        public virtual DbSet<t_ICItem> t_ICItem { get; set; }
        public virtual DbSet<PlanLog> PlanLog { get; set; }
        public virtual DbSet<StockWorks> StockWorks { get; set; }
        public virtual DbSet<StockWorkEntrys> StockWorkEntrys { get; set; }
        public virtual DbSet<InventQR> InventQR { get; set; }
        public virtual DbSet<InventVedomost> InventVedomost { get; set; }
        public virtual DbSet<InventSecondQR> InventSecondQR { get; set; }
        public virtual DbSet<InventThirdQR> InventThirdQR { get; set; }
        public virtual DbSet<t_ICItemMaterial> t_ICItemMaterial { get; set; }
        public virtual DbSet<LastDvigs> LastDvigs { get; set; }
        public virtual DbSet<StockBufer> StockBufer { get; set; }
        public virtual DbSet<PeremeshenieWorks> PeremeshenieWorks { get; set; }
        public virtual DbSet<PredNZP> PredNZP { get; set; }
        public virtual DbSet<DocumentLog> DocumentLog { get; set; }
        public virtual DbSet<vw_ic_cbcostobj> vw_ic_cbcostobj { get; set; }
        public virtual DbSet<PostuplenieNaSklad> PostuplenieNaSklad { get; set; }
        public virtual DbSet<QRTableNEW> QRTableNEW { get; set; }
        public virtual DbSet<DvigenieNEW> DvigenieNEW { get; set; }
        public virtual DbSet<ProverkaOTK> ProverkaOTK { get; set; }
        public virtual DbSet<NZPNEW> NZPNEW { get; set; }
        public virtual DbSet<SmenaHour> SmenaHour { get; set; }
        public virtual DbSet<wk_iot> wk_iot { get; set; }
        public virtual DbSet<PrichiniSpisaniya> PrichiniSpisaniya { get; set; }
        public virtual DbSet<t_BillCodeRule> t_BillCodeRule { get; set; }
        public virtual DbSet<BigQR> BigQR { get; set; }
        public virtual DbSet<ChasSmeni> ChasSmeni { get; set; }
        public virtual DbSet<MonitorToLine> MonitorToLine { get; set; }
        public virtual DbSet<YZActiveWorks> YZActiveWorks { get; set; }
        public virtual DbSet<YZRoles> YZRoles { get; set; }
        public virtual DbSet<YZRoleWorks> YZRoleWorks { get; set; }
        public virtual DbSet<YZUserDepartments> YZUserDepartments { get; set; }
        public virtual DbSet<YZUserRoles> YZUserRoles { get; set; }
        public virtual DbSet<YZUsers> YZUsers { get; set; }
        public virtual DbSet<YZWorks> YZWorks { get; set; }
        public virtual DbSet<EnteryLogs> EnteryLogs { get; set; }
        public virtual DbSet<StocksSelect> StocksSelect { get; set; }
        public virtual DbSet<GPScans> GPScans { get; set; }
        public virtual DbSet<InfoWorks> InfoWorks { get; set; }
        public virtual DbSet<InterfaceSelect> InterfaceSelect { get; set; }
        public virtual DbSet<SkladLog> SkladLog { get; set; }
    }
}
