//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MolsOfDepartments
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int MolId { get; set; }
    
        public virtual t_Item Department { get; set; }
        public virtual t_Item Mol { get; set; }
    }
}
