//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorToLine
    {
        public int Id { get; set; }
        public string MonitorIPAdress { get; set; }
        public int PlanshetId { get; set; }
    
        public virtual ComputerNames ComputerNames { get; set; }
    }
}
