//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenklaturaEnterprise
    {
        public string PartNumber { get; set; }
        public string RusName { get; set; }
        public string EnterpriseNumber { get; set; }
        public long Id { get; set; }
        public Nullable<int> KingDeeId { get; set; }
    
        public virtual t_Item t_Item { get; set; }
    }
}
