//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenklaturaPlace
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int DvigenieId { get; set; }
        public int StockId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public int StellagId { get; set; }
        public Nullable<int> PolkaId { get; set; }
        public Nullable<int> YacheikaId { get; set; }
    
        public virtual t_Item Item { get; set; }
        public virtual Street Street { get; set; }
        public virtual Yacheika Yacheika { get; set; }
        public virtual Dvigenie Dvigenie { get; set; }
        public virtual Planogramma Stellag { get; set; }
        public virtual Buildings Buildings { get; set; }
    }
}
