//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcheredWorks
    {
        public int Id { get; set; }
        public int WorkId { get; set; }
        public int Poryadok { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal QTY { get; set; }
        public int DepartmentId { get; set; }
        public int UserId { get; set; }
        public bool Vipolneno { get; set; }
        public string Prichina { get; set; }
        public bool Closed { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        public virtual t_Item Department { get; set; }
        public virtual ICMO ICMO { get; set; }
    }
}
