//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeremeshenieWorks
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public bool StockUchastka { get; set; }
        public bool BuferZona { get; set; }
    
        public virtual t_Item t_Item { get; set; }
    }
}
