//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POInStock
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<int> FCurrencyID { get; set; }
        public short FTranType { get; set; }
        public int FSupplyID { get; set; }
        public Nullable<int> FDeptID { get; set; }
        public Nullable<int> FEmpID { get; set; }
        public System.DateTime FDate { get; set; }
        public Nullable<int> FStockID { get; set; }
        public Nullable<int> FPosterID { get; set; }
        public Nullable<int> FCheckerID { get; set; }
        public Nullable<int> FBillerID { get; set; }
        public Nullable<int> FFManagerID { get; set; }
        public Nullable<int> FSManagerID { get; set; }
        public string FCnnBillNo { get; set; }
        public short FClosed { get; set; }
        public string FNote { get; set; }
        public Nullable<short> FInvoiceClosed { get; set; }
        public short FBClosed { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public Nullable<double> FExchangeRate { get; set; }
        public short FStatus { get; set; }
        public bool FCancellation { get; set; }
        public bool FUpStockWhenSave { get; set; }
        public Nullable<int> FPOStyle { get; set; }
        public Nullable<int> FMultiCheckLevel1 { get; set; }
        public Nullable<int> FMultiCheckLevel2 { get; set; }
        public Nullable<int> FMultiCheckLevel3 { get; set; }
        public Nullable<int> FMultiCheckLevel4 { get; set; }
        public Nullable<int> FMultiCheckLevel5 { get; set; }
        public Nullable<int> FMultiCheckLevel6 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate1 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate2 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate3 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate4 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate5 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate6 { get; set; }
        public Nullable<int> FCurCheckLevel { get; set; }
        public Nullable<int> FRelateBrID { get; set; }
        public string FExplanation { get; set; }
        public string FFetchAdd { get; set; }
        public string FSelectBillNo { get; set; }
        public int FSelTranType { get; set; }
        public int FChildren { get; set; }
        public Nullable<int> FBrID { get; set; }
        public int FTranStatus { get; set; }
        public int FAreaPS { get; set; }
        public string FReStatus { get; set; }
        public string FPOOrdBillNo { get; set; }
        public Nullable<int> FManageType { get; set; }
        public int FBizType { get; set; }
        public int FWWType { get; set; }
        public int FExchangeRateType { get; set; }
        public Nullable<int> FAccessoryCount { get; set; }
        public Nullable<int> FPOMode { get; set; }
        public int FPrintCount { get; set; }
        public int FIsCheck { get; set; }
    }
}
