//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POOrder()
        {
            this.POOrderEntry = new HashSet<POOrderEntry>();
            this.Dvigenie = new HashSet<Dvigenie>();
            this.NZP = new HashSet<NZP>();
            this.Komplekt = new HashSet<Komplekt>();
            this.ICStockBillEntry = new HashSet<ICStockBillEntry>();
            this.PostuplenieNaSklad = new HashSet<PostuplenieNaSklad>();
        }
    
        public string FBrNo { get; set; }
        public int FTranType { get; set; }
        public int FInterID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<int> FSupplyID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<int> FEmpID { get; set; }
        public Nullable<int> FDeptID { get; set; }
        public Nullable<int> FCurrencyID { get; set; }
        public Nullable<int> FCheckerID { get; set; }
        public Nullable<int> FBillerID { get; set; }
        public Nullable<int> FMangerID { get; set; }
        public short FClosed { get; set; }
        public int FTranStatus { get; set; }
        public Nullable<double> FExchangeRate { get; set; }
        public short FStatus { get; set; }
        public bool FCancellation { get; set; }
        public Nullable<int> FPOStyle { get; set; }
        public Nullable<int> FMultiCheckLevel1 { get; set; }
        public Nullable<int> FMultiCheckLevel2 { get; set; }
        public Nullable<int> FMultiCheckLevel3 { get; set; }
        public Nullable<int> FMultiCheckLevel4 { get; set; }
        public Nullable<int> FMultiCheckLevel5 { get; set; }
        public Nullable<int> FMultiCheckLevel6 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate1 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate2 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate3 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate4 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate5 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate6 { get; set; }
        public Nullable<int> FCurCheckLevel { get; set; }
        public Nullable<int> FRelateBrID { get; set; }
        public Nullable<int> FOrderAffirm { get; set; }
        public string FCashDiscount { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FExplanation { get; set; }
        public string FFetchAdd { get; set; }
        public Nullable<System.DateTime> FSettleDate { get; set; }
        public int FSettleID { get; set; }
        public int FSelTranType { get; set; }
        public int FChildren { get; set; }
        public Nullable<int> FBrID { get; set; }
        public string FPOOrdBillNo { get; set; }
        public int FAreaPS { get; set; }
        public int FClassTypeID { get; set; }
        public decimal FTotalCostFor { get; set; }
        public Nullable<System.DateTime> FlastModyDate { get; set; }
        public byte[] FOperDate { get; set; }
        public Nullable<int> FManageType { get; set; }
        public short FSysStatus { get; set; }
        public string FVersionNo { get; set; }
        public Nullable<System.DateTime> FChangeDate { get; set; }
        public string FChangeCauses { get; set; }
        public int FChangeMark { get; set; }
        public int FChangeUser { get; set; }
        public string FValidaterName { get; set; }
        public string FConsignee { get; set; }
        public short FPrintCount { get; set; }
        public int FExchangeRateType { get; set; }
        public string FDeliveryPlace { get; set; }
        public Nullable<int> FAccessoryCount { get; set; }
        public Nullable<int> FPOMode { get; set; }
        public int FPlanCategory { get; set; }
        public string FLastAlterBillNo { get; set; }
        public string FHeadSelfP0252 { get; set; }
        public string FMultiCheckStatus { get; set; }
        public string FHeadSelfP0253 { get; set; }
        public int FCloseUser { get; set; }
        public Nullable<System.DateTime> FCloseDate { get; set; }
        public string FCloseCauses { get; set; }
        public int FSendStatus { get; set; }
        public int FEnterpriseID { get; set; }
    
        public virtual t_Supplier t_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POOrderEntry> POOrderEntry { get; set; }
        public virtual t_Department t_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dvigenie> Dvigenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NZP> NZP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komplekt> Komplekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICStockBillEntry> ICStockBillEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostuplenieNaSklad> PostuplenieNaSklad { get; set; }
    }
}
