//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POOrderEntryPROD
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public int FEntryID { get; set; }
        public int FItemID { get; set; }
        public decimal FQty { get; set; }
        public decimal FCommitQty { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public decimal FPrice { get; set; }
        public decimal FAmount { get; set; }
        public Nullable<decimal> FTaxRate { get; set; }
        public Nullable<decimal> FTax { get; set; }
        public Nullable<decimal> FTaxAmount { get; set; }
        public string FNote { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxCommitQty { get; set; }
        public decimal FAuxPrice { get; set; }
        public decimal FAuxQty { get; set; }
        public int FSourceEntryID { get; set; }
        public decimal FCess { get; set; }
        public decimal FStockQty { get; set; }
        public decimal FAuxStockQty { get; set; }
        public string FMapNumber { get; set; }
        public string FMapName { get; set; }
        public decimal FAllAmount { get; set; }
        public int FAuxPropID { get; set; }
        public decimal FAuxPriceDiscount { get; set; }
        public decimal FPriceDiscount { get; set; }
        public decimal FQtyInvoice { get; set; }
        public decimal FQtyInvoiceBase { get; set; }
        public decimal FAuxTaxPrice { get; set; }
        public decimal FTaxPrice { get; set; }
        public decimal FReceiveAmountFor_Commit { get; set; }
        public decimal FReceiveAmount_Commit { get; set; }
        public decimal FSecCoefficient { get; set; }
        public decimal FSecQty { get; set; }
        public decimal FSecCommitQty { get; set; }
        public int FSourceTranType { get; set; }
        public int FSourceInterId { get; set; }
        public string FSourceBillNo { get; set; }
        public int FContractInterID { get; set; }
        public int FContractEntryID { get; set; }
        public string FContractBillNo { get; set; }
        public int FMRPLockFlag { get; set; }
        public decimal FAuxQtyInvoice { get; set; }
        public int FMrpClosed { get; set; }
        public int FDetailID { get; set; }
        public int FMapID { get; set; }
        public int FSProducingAreaID { get; set; }
        public decimal FAmtDiscount { get; set; }
        public decimal FCheckAmount { get; set; }
        public Nullable<int> FMrpAutoClosed { get; set; }
        public decimal FPayApplyAmountFor_Commit { get; set; }
        public decimal FPayApplyAmount_Commit { get; set; }
        public decimal FSecStockQty { get; set; }
        public decimal FSecInvoiceQty { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public decimal FDescount { get; set; }
        public string FSupConfirm { get; set; }
        public Nullable<System.DateTime> FSupConDate { get; set; }
        public Nullable<decimal> FSupConQty { get; set; }
        public string FSupConMem { get; set; }
        public Nullable<System.DateTime> FSupConFetchDate { get; set; }
        public Nullable<int> FSupConfirmor { get; set; }
        public int FQualityRptBillID { get; set; }
        public int FLockByAlter { get; set; }
        public decimal FDeliveryQty { get; set; }
        public decimal FAuxDeliveryQty { get; set; }
        public decimal FSecDeliveryQty { get; set; }
        public string FRejectRefuseNote { get; set; }
        public string FRefuseNote { get; set; }
        public byte FLockBySupplier { get; set; }
        public Nullable<int> FEntryAccessoryCount { get; set; }
        public int FPRInterID { get; set; }
        public int FPREntryID { get; set; }
        public Nullable<decimal> FAuxReceiptQty { get; set; }
        public Nullable<decimal> FReceiptQty { get; set; }
        public Nullable<decimal> FAuxReturnQty { get; set; }
        public Nullable<decimal> FReturnQty { get; set; }
        public int FCheckMethod { get; set; }
        public int FIsCheck { get; set; }
        public decimal FAmountExceptDisCount { get; set; }
        public decimal FAllAmountExceptDisCount { get; set; }
        public decimal FEntryDisCount { get; set; }
        public Nullable<decimal> FCommitAmt { get; set; }
        public Nullable<decimal> FCommitAmtTax { get; set; }
        public Nullable<decimal> FCommitTax { get; set; }
        public decimal FPayReqPayAmountFor { get; set; }
        public Nullable<decimal> FEntrySelfP0266 { get; set; }
        public string FEntrySelfP0268 { get; set; }
        public Nullable<decimal> FEntrySelfP0269 { get; set; }
        public Nullable<decimal> FEntrySelfP0270 { get; set; }
        public int FCloseEntryUser { get; set; }
        public Nullable<System.DateTime> FCloseEntryDate { get; set; }
        public string FCloseEntryCauses { get; set; }
        public int FOutSourceInterID { get; set; }
        public int FOutSourceEntryID { get; set; }
        public int FOutSourceTranType { get; set; }
        public string FBatchNo { get; set; }
    
        public virtual POOrderPROD POOrderPROD { get; set; }
    }
}
