//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORequest
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<int> FDeptID { get; set; }
        public Nullable<int> FRequesterID { get; set; }
        public Nullable<int> FBillerID { get; set; }
        public Nullable<int> FCheckerID { get; set; }
        public Nullable<System.DateTime> FCheckTime { get; set; }
        public string FNote { get; set; }
        public short FClosed { get; set; }
        public Nullable<short> FTranType { get; set; }
        public Nullable<short> FMRP { get; set; }
        public Nullable<int> FSCBillInterID { get; set; }
        public short FStatus { get; set; }
        public bool FCancellation { get; set; }
        public Nullable<int> FMrpClosed { get; set; }
        public Nullable<int> FMultiCheckLevel1 { get; set; }
        public Nullable<int> FMultiCheckLevel2 { get; set; }
        public Nullable<int> FMultiCheckLevel3 { get; set; }
        public Nullable<int> FMultiCheckLevel4 { get; set; }
        public Nullable<int> FMultiCheckLevel5 { get; set; }
        public Nullable<int> FMultiCheckLevel6 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate1 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate2 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate3 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate4 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate5 { get; set; }
        public Nullable<System.DateTime> FMultiCheckDate6 { get; set; }
        public Nullable<int> FCurCheckLevel { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FExplanation { get; set; }
        public int FSelTranType { get; set; }
        public int FChildren { get; set; }
        public Nullable<int> FMrpAutoClosed { get; set; }
        public int FBizType { get; set; }
        public bool FPlanConfirmed { get; set; }
        public decimal FGeneratePurBudQty { get; set; }
        public int FPrintCount { get; set; }
        public int FPlanCategory { get; set; }
        public int FAccessoryCount { get; set; }
    }
}
