//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostuplenieNaSklad
    {
        public int Id { get; set; }
        public int ZakazId { get; set; }
        public int ZakazEntryId { get; set; }
        public int PostavshikId { get; set; }
        public string ZakazNumber { get; set; }
        public string PostuplenieNumber { get; set; }
        public int PostuplenieId { get; set; }
        public int PostuplenieEntryId { get; set; }
        public int ItemId { get; set; }
        public decimal Qty { get; set; }
        public decimal PlanPrice { get; set; }
        public decimal FactPrice { get; set; }
        public int StockId { get; set; }
        public decimal QTYInStock { get; set; }
        public bool Proveden { get; set; }
        public bool Otmenen { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int UserId { get; set; }
        public int QRId { get; set; }
        public string PostavshikName { get; set; }
    
        public virtual POOrder POOrder { get; set; }
        public virtual t_Item t_Item { get; set; }
        public virtual DvigenieNEW DvigenieNEW { get; set; }
    }
}
