//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPBomChangeEntry
    {
        public int FEntryID { get; set; }
        public int FID { get; set; }
        public int FIndex { get; set; }
        public int FICMOInterID { get; set; }
        public string FICMOInterBN { get; set; }
        public int FProductItemID { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxQty { get; set; }
        public string FPPBomBillNo { get; set; }
        public int FPPBomEntryID { get; set; }
        public string FChangeFlag { get; set; }
        public string FChangeReason { get; set; }
        public int FItemID { get; set; }
        public int FBomInterID { get; set; }
        public string FMaterielType { get; set; }
        public decimal FAuxQtyScrap { get; set; }
        public int FItemUnitID { get; set; }
        public decimal FBOMInPutAuxQTY { get; set; }
        public decimal FScrap { get; set; }
        public decimal FAuxQtyLoss { get; set; }
        public decimal FAuxQtyPick { get; set; }
        public decimal FAuxQtyMust { get; set; }
        public Nullable<System.DateTime> FSendItemDate { get; set; }
        public int FStockID { get; set; }
        public int FSPID { get; set; }
        public string FBatchNo { get; set; }
        public string FBackFlush { get; set; }
        public int FOperSN { get; set; }
        public int FOperID { get; set; }
        public string FMachinePos { get; set; }
        public decimal FAuxStockQty { get; set; }
        public int FPPBOMInterID { get; set; }
        public decimal FDiscardAuxQty { get; set; }
        public string FLockFlag { get; set; }
        public decimal FAuxQtySupply { get; set; }
        public int FChangerID { get; set; }
        public Nullable<System.DateTime> FChangeDate { get; set; }
        public string FMark { get; set; }
        public decimal FQty { get; set; }
        public decimal FQtyScrap { get; set; }
        public decimal FBOMInPutQTY { get; set; }
        public decimal FQtyLoss { get; set; }
        public decimal FQtyPick { get; set; }
        public decimal FQtyMust { get; set; }
        public decimal FStockQty { get; set; }
        public decimal FDiscardQty { get; set; }
        public decimal FQtySupply { get; set; }
        public int FClassID_SRC { get; set; }
        public string FPositionNo { get; set; }
        public string FItemSize { get; set; }
        public string FItemSuite { get; set; }
        public string FNote1 { get; set; }
        public string FNote2 { get; set; }
        public string FNote3 { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public int FOrderEntryID { get; set; }
        public Nullable<bool> FIsRepItem { get; set; }
        public int FICSubsID { get; set; }
        public int FICSubsEntryID { get; set; }
        public short FIsKeyItem { get; set; }
        public int FPriorityID { get; set; }
        public int FAuxPropID { get; set; }
        public int FProductAuxPropID { get; set; }
        public Nullable<System.Guid> FBomDetailID { get; set; }
    }
}
