//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPBomChange
    {
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FBillNo { get; set; }
        public int FBillerID { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FCheckFlag { get; set; }
        public int FCheckerID { get; set; }
        public int FBillType { get; set; }
        public Nullable<System.DateTime> FCheckDateLong { get; set; }
        public string FText { get; set; }
    }
}
