//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPOrderEntry
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public int FEntryID { get; set; }
        public int FItemID { get; set; }
        public int FUnitID { get; set; }
        public decimal FQty { get; set; }
        public Nullable<System.DateTime> FNeedDate { get; set; }
        public string FNote { get; set; }
        public decimal FAuxQty { get; set; }
        public decimal FCommitQty { get; set; }
        public decimal FAuxCommitQty { get; set; }
        public int FSourceEntryID { get; set; }
        public Nullable<int> FHaveMrp { get; set; }
        public Nullable<int> FMrpClosed { get; set; }
        public Nullable<System.DateTime> FNeedDateEnd { get; set; }
        public int FSplitCycleID { get; set; }
        public Nullable<System.DateTime> FOrgNeedDate { get; set; }
        public Nullable<System.DateTime> FOrgNeedDateEnd { get; set; }
        public int FOrgEntryID { get; set; }
        public int FIsKilled { get; set; }
        public decimal FKillQty { get; set; }
        public decimal FAuxKillQty { get; set; }
        public int FBomInterID { get; set; }
        public int FCustID { get; set; }
        public decimal FSaleQty { get; set; }
        public decimal FAuxSaleQty { get; set; }
        public decimal FSelQty { get; set; }
        public decimal FAuxSelQty { get; set; }
        public int FOrderClosed { get; set; }
        public int FMRPLockFlag { get; set; }
        public int FSourceTranType { get; set; }
        public int FSourceInterID { get; set; }
        public string FSourceBillNo { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public int FDetailID { get; set; }
        public int FIsAPS { get; set; }
        public int FMeetDelivery { get; set; }
        public int FAuxPropID { get; set; }
        public int FBOMCategory { get; set; }
        public int FOrderBOMStatus { get; set; }
        public int FOrderBOMInterID { get; set; }
    }
}
