//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredNZP
    {
        public int Id { get; set; }
        public int QRId { get; set; }
        public string QRData { get; set; }
        public decimal QTY { get; set; }
        public int Etap { get; set; }
        public int WorkId { get; set; }
        public int StockWorkId { get; set; }
        public int ItemId { get; set; }
        public int StockId { get; set; }
    
        public virtual StockWorks StockWorks { get; set; }
    }
}
