//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTableNEW
    {
        public int Id { get; set; }
        public string WIN { get; set; }
        public int ItemId { get; set; }
        public int Lev { get; set; }
        public string QRString { get; set; }
    }
}
