//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladLog
    {
        public int Id { get; set; }
        public string FBillNo { get; set; }
        public int DocId { get; set; }
        public Nullable<decimal> QTYKPeremesheniu { get; set; }
        public int FromStockId { get; set; }
        public int ToId { get; set; }
        public string FromStockName { get; set; }
        public string ToName { get; set; }
        public decimal QTYBilo { get; set; }
        public decimal QTYStalo { get; set; }
        public int ItemId { get; set; }
        public string ItemNumber { get; set; }
    }
}
