//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmenaHour
    {
        public int Id { get; set; }
        public int PlanshetId { get; set; }
        public int QTYDatchik { get; set; }
        public int QTYFact { get; set; }
        public int QTYPlan { get; set; }
        public System.DateTime DateSmeni { get; set; }
        public int ChasSmeni { get; set; }
        public string Opisanie { get; set; }
    }
}
