//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockWorkEntrys
    {
        public int Id { get; set; }
        public int StockWorkId { get; set; }
        public decimal QTY { get; set; }
        public bool Complete { get; set; }
        public string Prichina { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public decimal Scrap { get; set; }
        public int ToStock { get; set; }
        public decimal QTYBufer { get; set; }
        public decimal QTYStock { get; set; }
        public decimal QTYDept { get; set; }
        public string ToBufer { get; set; }
        public int ToDepartment { get; set; }
        public bool SchemaBufer { get; set; }
        public bool SchemaStock { get; set; }
        public bool SchemaDept { get; set; }
        public int WorkId { get; set; }
    
        public virtual StockWorks StockWorks { get; set; }
        public virtual t_Item Item { get; set; }
        public virtual UsersKDW UsersKDW { get; set; }
    }
}
