//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksMOL
    {
        public Nullable<double> CEH { get; set; }
        public string RU { get; set; }
        public string ZH { get; set; }
        public string MOL { get; set; }
        public int Id { get; set; }
        public Nullable<int> FInterID { get; set; }
        public Nullable<int> MOLID { get; set; }
        public string FNumber { get; set; }
        public bool Actual { get; set; }
        public string YacheikaPriem { get; set; }
        public string YacheikaBufer { get; set; }
        public bool SkladUchastka { get; set; }
        public bool SkladBraka { get; set; }
        public bool SkladBrakaUchastka { get; set; }
    
        public virtual t_Stock t_Stock { get; set; }
        public virtual t_Item t_Item { get; set; }
        public virtual t_Item t_Item1 { get; set; }
    }
}
