//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_BillCodeRule
    {
        public int FID { get; set; }
        public string FBillTypeID { get; set; }
        public int FClassIndex { get; set; }
        public int FProjectID { get; set; }
        public string FProjectVal { get; set; }
        public int FFormatIndex { get; set; }
        public int FLength { get; set; }
        public string FAddChar { get; set; }
        public string FReChar { get; set; }
        public string FBillType { get; set; }
        public Nullable<int> FIsBy { get; set; }
    }
}
