//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Department()
        {
            this.POOrder = new HashSet<POOrder>();
            this.ICMO = new HashSet<ICMO>();
            this.ICStockBill = new HashSet<ICStockBill>();
            this.ComputerNames = new HashSet<ComputerNames>();
            this.ICSubContract = new HashSet<ICSubContract>();
            this.YZUserDepartments = new HashSet<YZUserDepartments>();
            this.YZWorks = new HashSet<YZWorks>();
        }
    
        public int FItemID { get; set; }
        public string FBrNO { get; set; }
        public Nullable<int> FManager { get; set; }
        public string FPhone { get; set; }
        public string FFax { get; set; }
        public string FNote { get; set; }
        public string FNumber { get; set; }
        public string FName { get; set; }
        public Nullable<int> FParentID { get; set; }
        public int FDProperty { get; set; }
        public Nullable<int> FDStock { get; set; }
        public short FDeleted { get; set; }
        public string FShortNumber { get; set; }
        public int FAcctID { get; set; }
        public int FCostAccountType { get; set; }
        public byte[] FModifyTime { get; set; }
        public int FCalID { get; set; }
        public Nullable<int> FPlanArea { get; set; }
        public int FOtherARAcctID { get; set; }
        public int FOtherAPAcctID { get; set; }
        public int FPreARAcctID { get; set; }
        public int FPreAPAcctID { get; set; }
        public bool FIsCreditMgr { get; set; }
        public bool FIsVDept { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POOrder> POOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMO> ICMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICStockBill> ICStockBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerNames> ComputerNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICSubContract> ICSubContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YZUserDepartments> YZUserDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YZWorks> YZWorks { get; set; }
    }
}
