//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ICItemMaterial
    {
        public int FItemID { get; set; }
        public Nullable<int> FOrderRector { get; set; }
        public Nullable<int> FPOHghPrcMnyType { get; set; }
        public Nullable<decimal> FPOHighPrice { get; set; }
        public Nullable<decimal> FWWHghPrc { get; set; }
        public Nullable<int> FWWHghPrcMnyType { get; set; }
        public Nullable<decimal> FSOLowPrc { get; set; }
        public Nullable<int> FSOLowPrcMnyType { get; set; }
        public Nullable<bool> FIsSale { get; set; }
        public Nullable<decimal> FProfitRate { get; set; }
        public Nullable<decimal> FSalePrice { get; set; }
        public Nullable<bool> FBatchManager { get; set; }
        public Nullable<bool> FISKFPeriod { get; set; }
        public Nullable<decimal> FKFPeriod { get; set; }
        public Nullable<int> FTrack { get; set; }
        public Nullable<decimal> FPlanPrice { get; set; }
        public Nullable<short> FPriceDecimal { get; set; }
        public Nullable<int> FAcctID { get; set; }
        public Nullable<int> FSaleAcctID { get; set; }
        public Nullable<int> FCostAcctID { get; set; }
        public Nullable<int> FAPAcctID { get; set; }
        public Nullable<int> FGoodSpec { get; set; }
        public Nullable<int> FCostProject { get; set; }
        public bool FIsSnManage { get; set; }
        public Nullable<bool> FStockTime { get; set; }
        public Nullable<bool> FBookPlan { get; set; }
        public Nullable<int> FBeforeExpire { get; set; }
        public Nullable<decimal> FTaxRate { get; set; }
        public Nullable<int> FAdminAcctID { get; set; }
        public string FNote { get; set; }
        public Nullable<bool> FIsSpecialTax { get; set; }
        public Nullable<decimal> FSOHighLimit { get; set; }
        public Nullable<decimal> FSOLowLimit { get; set; }
        public Nullable<decimal> FOIHighLimit { get; set; }
        public Nullable<decimal> FOILowLimit { get; set; }
        public Nullable<int> FDaysPer { get; set; }
        public Nullable<System.DateTime> FLastCheckDate { get; set; }
        public Nullable<int> FCheckCycle { get; set; }
        public Nullable<int> FCheckCycUnit { get; set; }
        public Nullable<decimal> FStockPrice { get; set; }
        public string FABCCls { get; set; }
        public Nullable<double> FBatchQty { get; set; }
        public Nullable<bool> FClass { get; set; }
        public Nullable<double> FCostDiffRate { get; set; }
        public Nullable<int> FDepartment { get; set; }
        public Nullable<int> FSaleTaxAcctID { get; set; }
        public int FCBBmStandardID { get; set; }
        public Nullable<int> FCBRestore { get; set; }
        public Nullable<decimal> FPickHighLimit { get; set; }
        public Nullable<decimal> FPickLowLimit { get; set; }
        public string FOnlineShopPName { get; set; }
        public string FOnlineShopPNo { get; set; }
        public Nullable<decimal> FUnitPackageNumber { get; set; }
        public int FOrderDept { get; set; }
        public bool FIsSNBanDing { get; set; }
        public bool FIsSNRpt { get; set; }
        public decimal FBarcodeQtyEachTime { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        public virtual LastDvigs LastDvigs { get; set; }
        public virtual t_Item t_Item1 { get; set; }
    }
}
