//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Stock()
        {
            this.StocksRusKit = new HashSet<StocksRusKit>();
            this.StocksMOL = new HashSet<StocksMOL>();
            this.ICInventory = new HashSet<ICInventory>();
            this.StockWorks = new HashSet<StockWorks>();
            this.StockBufer = new HashSet<StockBufer>();
            this.EntryTo = new HashSet<ICStockBillEntry>();
            this.DvigenieNEW = new HashSet<DvigenieNEW>();
            this.StocksSelect = new HashSet<StocksSelect>();
        }
    
        public int FItemID { get; set; }
        public string FBrNO { get; set; }
        public string FHelperCode { get; set; }
        public Nullable<int> FEmpID { get; set; }
        public string FAddress { get; set; }
        public string FPhone { get; set; }
        public Nullable<short> FProperty { get; set; }
        public Nullable<int> FBWorkShop { get; set; }
        public string FName { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> FParentID { get; set; }
        public short FDeleted { get; set; }
        public string FShortNumber { get; set; }
        public int FTypeID { get; set; }
        public bool FIsStockMgr { get; set; }
        public int FSPGroupID { get; set; }
        public bool FMRPAvail { get; set; }
        public int FGroupID { get; set; }
        public int FStockGroupID { get; set; }
        public byte[] FModifyTime { get; set; }
        public Nullable<int> FCalcCostOrder { get; set; }
        public Nullable<int> FPlanArea { get; set; }
        public int FUnderStock { get; set; }
        public bool FIncludeAccounting { get; set; }
        public byte FPTLEnable { get; set; }
        public byte FOutRule { get; set; }
    
        public virtual t_Item t_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocksRusKit> StocksRusKit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocksMOL> StocksMOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICInventory> ICInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockWorks> StockWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockBufer> StockBufer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICStockBillEntry> EntryTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DvigenieNEW> DvigenieNEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocksSelect> StocksSelect { get; set; }
    }
}
