//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_StockPlaceGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_StockPlaceGroup()
        {
            this.t_StockPlace = new HashSet<t_StockPlace>();
        }
    
        public int FSPGroupID { get; set; }
        public string FNumber { get; set; }
        public string FName { get; set; }
        public int FDefaultSPID { get; set; }
        public bool FDeleted { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_StockPlace> t_StockPlace { get; set; }
    }
}
