//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SupplyEntry
    {
        public string FBrNo { get; set; }
        public int FSupID { get; set; }
        public int FItemID { get; set; }
        public int FEntryID { get; set; }
        public int FUnitID { get; set; }
        public Nullable<decimal> FStartQty { get; set; }
        public decimal FEndQty { get; set; }
        public Nullable<decimal> FPrice { get; set; }
        public Nullable<int> FCyID { get; set; }
        public Nullable<decimal> FDiscount { get; set; }
        public Nullable<int> FLeadTime { get; set; }
        public Nullable<System.DateTime> FQuoteTime { get; set; }
        public bool FUsed { get; set; }
        public System.DateTime FDisableDate { get; set; }
        public string FRemark { get; set; }
        public int FPType { get; set; }
        public System.DateTime FLastModifiedDate { get; set; }
        public int FLastModifiedBy { get; set; }
        public Nullable<int> FCheckerID { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
    }
}
