//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Supply
    {
        public string FBrNo { get; set; }
        public int FSupID { get; set; }
        public int FItemID { get; set; }
        public int FCurrencyID { get; set; }
        public decimal FPOHighPrice { get; set; }
        public int FPType { get; set; }
    }
}
