//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Supplier()
        {
            this.POOrder = new HashSet<POOrder>();
            this.ICSubContract = new HashSet<ICSubContract>();
            this.ICStockBill = new HashSet<ICStockBill>();
        }
    
        public int FItemID { get; set; }
        public string FAddress { get; set; }
        public string FCity { get; set; }
        public string FProvince { get; set; }
        public string FCountry { get; set; }
        public string FPostalCode { get; set; }
        public string FPhone { get; set; }
        public string FFax { get; set; }
        public string FEmail { get; set; }
        public string FHomePage { get; set; }
        public string FCreditLimit { get; set; }
        public string FTaxID { get; set; }
        public string FBank { get; set; }
        public string FAccount { get; set; }
        public string FBrNo { get; set; }
        public Nullable<int> FBoundAttr { get; set; }
        public Nullable<int> FErpClsID { get; set; }
        public string FShortName { get; set; }
        public Nullable<int> FPriorityID { get; set; }
        public Nullable<int> FPOGroupID { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FLanguageID { get; set; }
        public Nullable<int> FRegionID { get; set; }
        public Nullable<int> FTrade { get; set; }
        public Nullable<double> FMinPOValue { get; set; }
        public Nullable<double> FMaxDebitDate { get; set; }
        public string FLegalPerson { get; set; }
        public string FContact { get; set; }
        public string FContactAcct { get; set; }
        public string FPhoneAcct { get; set; }
        public string FFaxAcct { get; set; }
        public string FZipAcct { get; set; }
        public string FEmailAcct { get; set; }
        public string FAddrAcct { get; set; }
        public Nullable<float> FTax { get; set; }
        public Nullable<int> FCyID { get; set; }
        public Nullable<int> FSetID { get; set; }
        public Nullable<int> FSetDLineID { get; set; }
        public string FTaxNum { get; set; }
        public Nullable<int> FPriceClsID { get; set; }
        public Nullable<int> FOperID { get; set; }
        public string FCIQNumber { get; set; }
        public short FDeleted { get; set; }
        public short FSaleMode { get; set; }
        public string FName { get; set; }
        public string FNumber { get; set; }
        public int FParentID { get; set; }
        public string FShortNumber { get; set; }
        public int FARAccountID { get; set; }
        public int FAPAccountID { get; set; }
        public int FpreAcctID { get; set; }
        public decimal FlastTradeAmount { get; set; }
        public decimal FLastRPAmount { get; set; }
        public string FFavorPolicy { get; set; }
        public int Fdepartment { get; set; }
        public int Femployee { get; set; }
        public string Fcorperate { get; set; }
        public Nullable<System.DateTime> FBeginTradeDate { get; set; }
        public Nullable<System.DateTime> FEndTradeDate { get; set; }
        public Nullable<System.DateTime> FLastTradeDate { get; set; }
        public Nullable<System.DateTime> FLastReceiveDate { get; set; }
        public string FcashDiscount { get; set; }
        public int FcurrencyID { get; set; }
        public double FMaxDealAmount { get; set; }
        public double FMinForeReceiveRate { get; set; }
        public double FMinReserveRate { get; set; }
        public double FMaxForePayAmount { get; set; }
        public double FMaxForePayRate { get; set; }
        public int FdebtLevel { get; set; }
        public int FCreditDays { get; set; }
        public Nullable<decimal> FValueAddRate { get; set; }
        public int FPayTaxAcctID { get; set; }
        public decimal FDiscount { get; set; }
        public int FTypeID { get; set; }
        public Nullable<decimal> FCreditAmount { get; set; }
        public string FCreditLevel { get; set; }
        public int FStockIDAssignee { get; set; }
        public int FBr { get; set; }
        public string FRegmark { get; set; }
        public bool FLicAndPermit { get; set; }
        public string FLicence { get; set; }
        public Nullable<System.DateTime> FPaperPeriod { get; set; }
        public Nullable<int> FAlarmPeriod { get; set; }
        public int FOtherARAcctID { get; set; }
        public int FOtherAPAcctID { get; set; }
        public int FPreARAcctID { get; set; }
        public string FHelpCode { get; set; }
        public byte[] FModifyTime { get; set; }
        public string FNameEN { get; set; }
        public string FAddrEn { get; set; }
        public string FCIQCode { get; set; }
        public Nullable<int> FRegion { get; set; }
        public string FMobilePhone { get; set; }
        public Nullable<int> FManageType { get; set; }
        public Nullable<System.DateTime> FRegsterDate { get; set; }
        public Nullable<System.DateTime> FPassDate { get; set; }
        public Nullable<System.DateTime> FInureDate { get; set; }
        public Nullable<System.DateTime> FAbateDate { get; set; }
        public int FSupplyGrade { get; set; }
        public Nullable<int> FSupplyType { get; set; }
        public Nullable<int> FCompanyType { get; set; }
        public int FEvalutionType { get; set; }
        public bool FSupplierCoroutineFlag { get; set; }
        public bool FAutoCreateMR { get; set; }
        public Nullable<bool> FAutoValidateOrderFlag { get; set; }
        public Nullable<bool> FAPFrozenFlag { get; set; }
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public int FBiller { get; set; }
        public int FModifier { get; set; }
        public Nullable<System.DateTime> FBillDate { get; set; }
        public Nullable<System.DateTime> FModifyDate { get; set; }
        public string FScale { get; set; }
        public string FCharacter { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public decimal FRegsterAmount { get; set; }
        public string FProducePermit { get; set; }
        public int FSumPepole { get; set; }
        public decimal FPrepayAmount { get; set; }
        public int FIsAutoNumber { get; set; }
        public int FVMIStockID { get; set; }
        public int FPOMode { get; set; }
        public Nullable<System.DateTime> FSRMStartDate { get; set; }
        public int FProvinceID { get; set; }
        public string F1688MemberId { get; set; }
        public int FCityID { get; set; }
        public string F_102 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POOrder> POOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICSubContract> ICSubContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICStockBill> ICStockBill { get; set; }
    }
}
