//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_User
    {
        public int FUserID { get; set; }
        public string FName { get; set; }
        public string FSID { get; set; }
        public byte[] PasswordHashValue { get; set; }
        public System.Guid ID { get; set; }
        public short FPrimaryGroup { get; set; }
        public string FDescription { get; set; }
        public string FPortUser { get; set; }
        public Nullable<bool> FForbidden { get; set; }
        public byte[] FRight { get; set; }
        public Nullable<int> FEmpID { get; set; }
        public Nullable<int> FDataVokeType { get; set; }
        public Nullable<bool> FIsNeedOffline { get; set; }
        public Nullable<bool> FRightChanged { get; set; }
        public Nullable<bool> FOfflineRefeshEachTime { get; set; }
        public Nullable<int> FSafeMode { get; set; }
        public string FSupplierID { get; set; }
        public Nullable<int> FHRUser { get; set; }
        public string FSSOUsername { get; set; }
        public string FSCPwd { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public Nullable<int> FAccessUUID { get; set; }
        public Nullable<System.DateTime> FUInValidDate { get; set; }
        public Nullable<System.DateTime> FPwCreateDate { get; set; }
        public Nullable<int> FPwValidDay { get; set; }
        public Nullable<int> FAuthRight { get; set; }
        public Nullable<int> FUserTypeID { get; set; }
        public byte[] FModifyTime { get; set; }
        public Nullable<int> FCustomerID { get; set; }
        public string FIMUserName { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public string FSupUnit { get; set; }
        public Nullable<int> FYZJSafeMode { get; set; }
    
        public virtual t_Item t_Item { get; set; }
    }
}
