//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersKDW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersKDW()
        {
            this.KingDeeWebRoles = new HashSet<KingDeeWebRoles>();
            this.DepartmentsToUsers = new HashSet<DepartmentsToUsers>();
            this.Dvigenie = new HashSet<Dvigenie>();
            this.StockWorks = new HashSet<StockWorks>();
            this.StockWorkEntrys = new HashSet<StockWorkEntrys>();
            this.InventQR = new HashSet<InventQR>();
            this.InventVedomost = new HashSet<InventVedomost>();
            this.InventSecondQR = new HashSet<InventSecondQR>();
            this.InventThirdQR = new HashSet<InventThirdQR>();
        }
    
        public int Id { get; set; }
        public int Password { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public int MOLId { get; set; }
    
        public virtual t_Base_User t_Base_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KingDeeWebRoles> KingDeeWebRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentsToUsers> DepartmentsToUsers { get; set; }
        public virtual t_Item t_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dvigenie> Dvigenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockWorks> StockWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockWorkEntrys> StockWorkEntrys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventQR> InventQR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventVedomost> InventVedomost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventSecondQR> InventSecondQR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventThirdQR> InventThirdQR { get; set; }
    }
}
