//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yacheika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yacheika()
        {
            this.NomenklaturaPlace = new HashSet<NomenklaturaPlace>();
        }
    
        public int Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Z { get; set; }
        public int H { get; set; }
        public int W { get; set; }
        public string C { get; set; }
        public string Name { get; set; }
        public int Num { get; set; }
        public int StockId { get; set; }
        public int PlanogrammaId { get; set; }
    
        public virtual Planogramma Planogramma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NomenklaturaPlace> NomenklaturaPlace { get; set; }
    }
}
