//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YZActiveWorks
    {
        public int Id { get; set; }
        public int WorkId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Comment { get; set; }
        public bool Complete { get; set; }
    
        public virtual YZWorks YZWorks { get; set; }
        public virtual YZUsers YZUsers { get; set; }
    }
}
