//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YZRoleWorks
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int WorkId { get; set; }
    
        public virtual YZRoles YZRoles { get; set; }
        public virtual YZWorks YZWorks { get; set; }
    }
}
